- lib/kafka/cluster.rb
- lib/kafka/connection.rb
- spec/connection_spec.rb
* Require an open socket when initializing.
* Set up encoder and decoder when initializing.
> Simplify Connection

- lib/kafka/broker.rb
- lib/kafka/broker_pool.rb
- lib/kafka/client.rb
- lib/kafka/connection.rb
> Enforce configurable timeouts when using a socket

- lib/kafka/connection.rb
- lib/kafka/producer.rb
- spec/broker_spec.rb
> All timeouts should be in seconds

- Gemfile
- spec/spec_helper.rb
- spec/test_cluster.rb
> Use Docker containers to build a test cluster

- bin/console
- kafka.gemspec
Not a big deal, but I always find pry better for poking around and exploring (`cd` ftw)
> Use pry for the console.

- README.md
- lib/kafka/producer.rb
- spec/functional/producer_spec.rb
- spec/producer_spec.rb
* Rename `#write` to `#produce`.
* Rename `#flush` to `#send_messages`.
> Change the Producer API

- README.md
- 👍boost confidence to people evaluating your open source library!
- 🙆raise awareness of all your beautiful tests!
- 🔚broken builds!
- 👻scare away bad bugs!
- 👓look really cool in the eyes of your friends and coworkers!
> Add circleci badge to readme

- lib/kafka/connection.rb
- lib/kafka/instrumentation.rb
- lib/kafka/protocol.rb
- ruby-kafka.gemspec
- spec/connection_spec.rb
- spec/spec_helper.rb
> Add support for instrumentation

- lib/kafka/client.rb
I'm not quite sure what the best default policy should be here. We could also just log to STDERR unless instructed otherwise?
> Add a default logger

- lib/kafka/produce_operation.rb
- lib/kafka/producer.rb
"Operation" better captures what it does, and the concept applies more broadly.
> Rename Transmission to ProduceOperation

- README.md
- Rakefile
- lib/kafka/fetch_operation.rb
- lib/kafka/fetched_message.rb
- lib/kafka/instrumentation.rb
- lib/kafka/socket_with_timeout.rb
- ruby-kafka.gemspec
Removing trailing spaces, prefer using regular quotation instead of `%q`, etc.
I noticed that there is no spec covering the `if offset < 0` condition that I have changed. That may be an oversight.
@dasch
> Cleaning up here and there

- lib/kafka/partitioner.rb
- lib/kafka/producer.rb
- spec/partitioner_spec.rb
There's no reason to keep that stuff in Producer.
> Move more partitioning logic into Partitioner

- lib/kafka/produce_operation.rb
- lib/kafka/producer.rb
Instruments the producer at two levels:
* `send_messages.kafka` – individual delivery attempts. The duration includes only the serialization, network, and server time spent delivering the messages.
* `deliver_messages.kafka` – a full delivery loop, including any retries, backoffs, cluster discoveries, etc. This will be the sum of `send_messages.kafka` durations.
The latter notification captures the duration of time the caller is blocked, and so is important to track. The former notification more granularly captures network and server performance.
I'm not entirely sure about the send/deliver nomenclature.
> Instrument producer operations

- lib/kafka/client.rb
- lib/kafka/cluster.rb
- spec/functional/client_spec.rb
> Allow fetching the partition count for a topic

- lib/kafka/compression.rb
- lib/kafka/fetch_operation.rb
- lib/kafka/gzip_codec.rb
- lib/kafka/produce_operation.rb
- lib/kafka/producer.rb
- lib/kafka/protocol/message.rb
- lib/kafka/protocol/message_set.rb
- lib/kafka/protocol/produce_request.rb
- lib/kafka/snappy_codec.rb
- ruby-kafka.gemspec
- spec/fake_broker.rb
- spec/functional/compression_spec.rb
- spec/protocol/message_set_spec.rb
Implementation of #7.
Adds support for Snappy and Gzip compression, both when producing and when fetching messages.
> Implement compression

- lib/kafka/async_producer.rb
- spec/async_producer_spec.rb
The producer thread should not dequeue operations as long as the underlying sync producer has a full buffer. Instead, the queue should start filling up, eventually propagating the buffer overflow error to the calling thread.
The implementation in this PR will rescue buffer overflows raised by the sync producer and call `#deliver_messages` until `#produce` no longer raises BufferOverflow. This could quite possibly be a bad idea, depending on the retry backoff time of the sync producer.
> Block the async producer thread during buffer overflows

- lib/kafka/compressor.rb
Adds a notification `compress.compressor.kafka`. Not sure if it should just be `compress.kafka`...
> Instrument Compressor

- lib/kafka/consumer.rb
The default offset specifies the offset to read from in case there hasn't been an offset commit for a given partition. It's effectively the offset to start from when you first deploy a consumer group.
> Allow configuring the default offset when subscribing to topics

- lib/kafka/consumer.rb
- lib/kafka/offset_manager.rb
* Extracts offset management code into OffsetManager.
* Makes the consumer commit its offsets on shutdown.
* Makes the consumer clear its offsets cache when re-joining a group.
> Refactor consumer offset management

- lib/kafka/client.rb
- lib/kafka/producer.rb
- spec/producer_spec.rb
Move defaults and docs to Client.
> Move Producer initialization to Client

- lib/kafka/consumer.rb
Work in progress. Not sure about thread safety here.
> Allow stopping a consumer loop

- lib/kafka/producer.rb
> Raise DeliveryFailed when partition assignment fails

- lib/kafka/async_producer.rb
In some contexts, such as when starting a producer in a Rails initializer and using Unicorn as the web server, producer threads may die because the process forks. By starting the threads lazily, we postpone initialization until the fork has completed, thus avoiding the problem.
Should fix #162.
> Lazily start async producer threads

- lib/kafka/producer.rb
> Instrument buffer overflows in the producer

- lib/kafka/protocol/offset_commit_request.rb
-1 should be used in order to use the broker default.
> The wrong value was used for the offset commit retention time

- lib/kafka/offset_manager.rb
> clear committed_offsets after commit offsets

- lib/kafka/message_buffer.rb
- spec/message_buffer_spec.rb
- must reset bytesize or appending a message on a cleared
buffer will fail w/ a Max buffer bytesize exception
> fix MessageBuffer#clear

- lib/kafka/client.rb
While the main client instance retains its Cluster, the consumer and producer instances now get their own, allowing them to be used from separate threads.
> Use separate connection pools for consumers and producers

- lib/kafka/fetch_operation.rb
> Added Kafka::ConnectionError to fix #194

- README.md
- lib/kafka/client.rb
- lib/kafka/producer.rb
The default setting should be the safest one.
> Improve the default durability setting

- .gitignore
- Gemfile.lock
- Procfile
- Rakefile
- ci/consumer.rb
- ci/init.rb
- ci/producer.rb
- ruby-kafka.gemspec
* Remove the Rakefile, it caused build issues.
* Loosen the dependency on Active Support, bundler had problems.
* Add a consumer/producer pair.
> Add continuous integration on Heroku

- lib/kafka/offset_manager.rb
- spec/functional/consumer_group_spec.rb
An error in arithmetic caused the consumer to fetch new messages starting not from the last offset that had been committed, but the offset immediately preceding it.
> Don't re-fetch the same message twice

- spec/test_cluster.rb
> Fix starting test cluster

- lib/kafka/ssl_socket_with_timeout.rb
We've been seeing a case where Kafka won't accept new SSL connections
properly. It accepts the TCP one, but doesn't perform the SSL handshake
properly. The SSL socket behaviour in this library doesn't handle this
case properly.
This clears up the logic in this class as well to use a
`select_with_timeout` method (taken from
https://github.com/excon/excon/blob/192bb842e70b550ed6d78c6d621962ee0faca4be/lib/excon/socket.rb)
I've tested this against a broken production Kafka and this does indeed get a proper timeout.
> fix ssl socket timeout

- spec/test_cluster.rb
This should fix https://github.com/zendesk/ruby-kafka/issues/238
> Get functional tests working with Docker for Mac

- lib/kafka/produce_operation.rb
This can be useful in order to track the offsets written.
Fixes #307.
> Add offset info to ack notifications

- lib/kafka/fetched_batch.rb
- spec/fetched_batch_spec.rb
> Fix batch offset lag

- lib/kafka/consumer.rb
> Update topic metadata when leader not available

- lib/kafka/consumer.rb
- spec/consumer_spec.rb
As discussed in #355 implemented a method for exposing heartbeat from a consumer.
@michaelsauter FYI
> Add method to send heartbeat if necessary on consumer

- README.md
- lib/kafka/client.rb
- lib/kafka/connection_builder.rb
- lib/kafka/protocol/sasl_handshake_request.rb
- lib/kafka/sasl_plain_authenticator.rb
- spec/connection_spec.rb
- spec/fake_server.rb
- spec/protocol/sasl_handshake_request_spec.rb
- spec/sasl_plain_authenticator_spec.rb
> Working SASL_PLAIN

- lib/kafka/producer.rb
- spec/producer_spec.rb
When a message fails to receive a partition, all subsequent messages for the same topic should be queued for retry because it is possible that they should follow the message that failed to receive a partition and we do not want to lose ordering.
We were intermittently getting messages out of order in our tests due to this bug.
> Retry subsequent messages for a topic after failing to assign a partition

- circle.yml
- lib/kafka/fetch_operation.rb
- lib/kafka/fetched_message.rb
- lib/kafka/protocol/fetch_request.rb
- lib/kafka/protocol/fetch_response.rb
- lib/kafka/protocol/message.rb
- lib/kafka/protocol/produce_request.rb
- lib/kafka/protocol/produce_response.rb
- spec/consumer_spec.rb
- spec/fake_broker.rb
- spec/test_cluster.rb
This builds upon #279 by @yingnanliu.
> Add support for Kafka 0.10 message timestamps

- Gemfile.lock
- lib/kafka/sasl_gssapi_authenticator.rb
- ruby-kafka.gemspec
* Do not require gssapi as a runtime gem
> Allow to lazily load "gssapi" gem

- lib/kafka/cluster.rb
Right now ruby-kafka reports `ConnectionError` when initializing
metadata from a cluster. This can happen just because the metadata
response timed out being read from the broker.
Instead, as well as logging the error and which broker it was regarding,
actually output that in the `ConnectionError` exception
> show the underlying error on metadata fetching issues

- lib/kafka/client.rb
- lib/kafka/consumer_group.rb
- lib/kafka/datadog.rb
- lib/kafka/statsd.rb
> Improve consumer group metrics

- .rubocop.yml
- Gemfile.lock
- ci/init.rb
- circle.yml
- lib/kafka/client.rb
- lib/kafka/consumer.rb
- lib/kafka/sasl_gssapi_authenticator.rb
- lib/kafka/ssl_socket_with_timeout.rb
- lib/kafka/statsd.rb
- ruby-kafka.gemspec
- spec/consumer_spec.rb
- spec/fake_broker.rb
- spec/fetched_batch_spec.rb
- spec/functional/consumer_group_spec.rb
- spec/sasl_authenticator_spec.rb
- spec/test_cluster.rb
RuboCop makes code look nicer. Here, most cops are disabled so only some Layout cops are enabled.
> Run RuboCop on CI

- lib/kafka/client.rb
- spec/client_spec.rb
Due to #415 I think it would be an improvement to UX if we validate these URIs at setup time.
> Validate the URI scheme of seed brokers

- lib/kafka/produce_operation.rb
Debugging would be easier if we knew which broker returned the error.
> Include broker info in logs

- README.md
This PR adds README documentation of the consumer instrumentation. I tried to mirror the style of the producer instrumentation doc.
> Document consumer instrumentation

- lib/kafka/statsd.rb
Is it possible to merge this to 0.4.x release too ?
> Report consumer lag to StatsD when processing batches

- lib/kafka/protocol/message.rb
Even if a cluster has been upgraded to Kafka protocol version 0.10, we may still get messages in the 0.9 format.
Fixes #445.
> Decode 0.9-format messages

- lib/kafka/connection.rb
- lib/kafka/consumer.rb
- lib/kafka/socket_with_timeout.rb
- spec/consumer_spec.rb
> Instantly kill socket reads on consumer shutdown

- lib/kafka/broker.rb
- lib/kafka/client.rb
- lib/kafka/cluster.rb
- lib/kafka/protocol.rb
- lib/kafka/protocol/create_topics_request.rb
- lib/kafka/protocol/create_topics_response.rb
- lib/kafka/protocol/decoder.rb
- lib/kafka/protocol/encoder.rb
- lib/kafka/protocol/metadata_response.rb
- lib/kafka/protocol/topic_metadata_request.rb
- spec/broker_spec.rb
- spec/cluster_spec.rb
- spec/functional/client_spec.rb
- spec/functional/topic_management_spec.rb
- spec/spec_helper.rb
> Support the topic creation API

- lib/kafka/round_robin_assignment_strategy.rb
It's not really useful unless you know which topic is missing.
> Improve error message for UnknownTopicOrPartition

- README.md
I've read today some docs, and noticed, that the readme is getting a bit confusion on this one, so updated.
> Higher level libraries better description

- lib/kafka/compression.rb
- lib/kafka/gzip_codec.rb
- lib/kafka/lz4_codec.rb
- lib/kafka/snappy_codec.rb
Fixes a regression introduced by #509.
> Lazy load compressors

- lib/kafka/consumer_group.rb
The "sending heartbeat" message is spamming our logs. I'd like to propose to switching that to debug.
> change log message to debug

- spec/functional/consumer_group_spec.rb
Add one more test to ensure each consumer consumes the messages in-order, non-duplicate and non-missing; from the recommendation https://github.com/zendesk/ruby-kafka/issues/527
> Add more tests to ensure consumer properties

- lib/kafka/client.rb
- lib/kafka/sasl_authenticator.rb
> Ensure SSL is configured when SASL auth is used

- lib/kafka/consumer.rb
- lib/kafka/datadog.rb
- lib/kafka/pause.rb
- lib/kafka/statsd.rb
This gauges the duration of each partition pause.
> Instrument the duration of pauses

- lib/kafka/ssl_socket_with_timeout.rb
> Use mutable String constructor

- lib/kafka/broker.rb
- lib/kafka/client.rb
- lib/kafka/cluster.rb
- lib/kafka/protocol.rb
- lib/kafka/protocol/describe_groups_request.rb
- lib/kafka/protocol/describe_groups_response.rb
- spec/functional/client_spec.rb
Should merge after https://github.com/zendesk/ruby-kafka/pull/582
> Add describe groups API

- lib/kafka/client.rb
- lib/kafka/fetcher.rb
> Configurable fetcher max queue size

- README.md
Fix version number in Compatibility section of README.md
A typo in README.md for version compatibility.
> Fix compatibility version in documentation

- CHANGELOG.md
- lib/kafka/async_producer.rb
> Synchronize @worker_thread and @timer_thread in AsyncProducer

- README.md
- lib/kafka/client.rb
- lib/kafka/ssl_context.rb
I'm in need of this functionality and #596 is waiting on a PR
> Support specifying an ssl client certificates key passphrase

- lib/kafka/tagged_logger.rb
See discussion in #716. This is an attempt at turning this into a separate class rather than modifying the underlying logger. Hopefully this will fix some of the issues we've been seeing.
@dasch
> Change TaggedLogger to use a class implementation

- lib/kafka/prometheus.rb
- ruby-kafka.gemspec
- spec/prometheus_spec.rb
I have added support for sending metric using the prometheus/client gem. More or less a copy of the statsd support.
> Added metrics for prometheus/client

- lib/kafka/sasl/scram.rb
Fix for issue #736 
Invalid server signature was raise because client mixed server_signature between threads.
> Scram authentication thread save

- lib/kafka/ssl_context.rb
> Fix SSL authentication for ruby < 2.4.0

- lib/kafka/tagged_logger.rb
This should enable custom loggers again. Tested with Logging framework.
> #756: Fix logger again

- .circleci/config.yml
- README.md
- add kafka `2.2.1`
- update `2.1.0` to `2.1.1`
> add kafka 2.2.1 to CI

- spec/functional/topic_management_spec.rb
Closes https://github.com/zendesk/ruby-kafka/issues/796
I noticed when running CI on https://github.com/zendesk/ruby-kafka/pull/795 that `create partitions` was failing on a single Kafka version, which seemed weird.  That particular test also depends on the topic metadata getting updated, which may be subject to a race condition.
To fix this, I'm adding a retry to that particular case (and including a small `with_retry` function to accomplish that).  I investigated using https://github.com/NoRedInk/rspec-retry or https://github.com/rstacruz/rspec-repeat, however those wrap the entire `example` block when in this particular case we only want the `expect` to be retried.
> Add retries to create partitions test

- lib/kafka/client.rb
- lib/kafka/cluster.rb
- lib/kafka/protocol/offset_fetch_request.rb
- spec/functional/client_spec.rb
Resolves #785 
@dasch 
Not sure if there's a better approach to the api version logic. Lemme know what you think!
I'll take a stab at writing some tests if this looks good!
> Expose method for fetching all group offsets

- lib/kafka/consumer.rb
Fixes #836
It lacks specs though.
> Fix getting last message time

- .circleci/config.yml
- README.md
Compatibility check for Kafka 2.6.0
> Add kafka 2.6.0 to Circle CI

- spec/functional/client_spec.rb
Doesn't seem important, removing.
> This spec stopped working at some point

- CHANGELOG.md
- README.md
- lib/kafka/client.rb
- lib/kafka/protocol/sasl_handshake_request.rb
- lib/kafka/sasl/awsmskiam.rb
- lib/kafka/sasl_authenticator.rb
- lib/kafka/version.rb
- spec/sasl_authenticator_spec.rb
I am opening up this PR to expand on the work that @jobeus started in https://github.com/zendesk/ruby-kafka/pull/907 since it has been over a month since the last update. If the maintainers prefer, feel free to fold these updates into the original PR.
Updates from the original PR:
* Added session token to the IAM mechanism. This is necessary for auth via temporary credentials such as those returned when assuming a role.
* Fixed broken unit tests
> AWS MSK IAM auth

- .circleci/config.yml
* wurstmeister/kafka:2.13-2.7.0 has an issue with missing zstd support which causes a spec to fail: https://github.com/wurstmeister/kafka-docker/issues/669
> Update CI and Tests

- README.md
- ruby-kafka.gemspec
As discussed, it would be good to add deprec notice for folks plus warning in a post install message
> Add deprecation notice
