- lib/kafka/broker.rb
- lib/kafka/connection.rb
- lib/kafka/protocol/metadata_response.rb
- lib/kafka/protocol/produce_response.rb
* Rather than having clients of Connection call `write_request` and `read_response` directly, provide a single entrypoint: `request`.
* Instead of having response instances decode themselves, pass the class of the response and let that instantiate an object with the decoded data. This could be extended to use completely separate classes for decoding, e.g. ProduceResponseDecoder. Let's not go all Java on this, though.
> Simplify request/response handling

- lib/kafka/broker_pool.rb
- lib/kafka/partitioner.rb
- lib/kafka/producer.rb
- lib/kafka/protocol/metadata_response.rb
- spec/functional/producer_spec.rb
If `Producer#write` is passed a `partition_key` parameter, it will be used to compute the partition to which the message will be written. If neither `partition` nor `partition_key` is specified, the message key will be used instead.
Implements #9.
> Allow automatic partition assignment

- lib/kafka.rb
- lib/kafka/broker.rb
- lib/kafka/broker_pool.rb
- spec/functional/producer_spec.rb
- spec/spec_helper.rb
- spec/test_cluster.rb
When flushing messages to the cluster, we initially discover the leaders for the partitions we need to write to. If one of the leaders has become unavailable since we last discovered the cluster, we'll have to rediscover it to find out which nodes have taken over leadership of the partitions previously owned by that node. Then we can retry. Since leader election is not instantaneous, we need to back off before trying again.
There's still a chance that one of the nodes becomes unavailable between the time we discover the partition leaders and the time we try to actually send the messages to those nodes – that case has not yet been handled, and is left for a future PR.
> Retry produce requests on node failure

- lib/kafka/broker_pool.rb
A small PR to add the used RETRY_BACKOFF_TIMEOUT in the logs.
Tests are green locally.
@dasch
> Log RETRY_BACKOFF_TIMEOUT

- lib/kafka/partitioner.rb
- lib/kafka/producer.rb
- spec/functional/producer_spec.rb
- spec/partitioner_spec.rb
If a message key is not passed, and there's no explicit partition or partition key specified either, the partition is picked at random.
> Make message keys optional

- lib/kafka.rb
- lib/kafka/broker_pool.rb
- lib/kafka/message_buffer.rb
- lib/kafka/producer.rb
- lib/kafka/protocol/produce_response.rb
- spec/functional/producer_spec.rb
- spec/message_buffer_spec.rb
- spec/producer_spec.rb
- spec/test_cluster.rb
See the code documentation for a description of the design. If you have questions, I'd like to answer them in the docs rather than here :-)
I'd like to get some feedback on the design of the error handling. Specifically the way the buffer is used. In the current design, calling `flush` would never fail with an exception – rather, a bunch of errors would be logged and the buffer would retain all messages that could not be written. Alternatively, `flush` could raise an exception if any messages are left in the buffer after all attempts have been exhausted, but I'm not sure what the value of that would be. For us at least, it would be better to just keep running.
I'll have to implement a max buffer size, though, so eventually the client code would run into trouble. But with sufficient …
> Implement error handling and retry logic

- lib/kafka/connection.rb
- spec/connection_spec.rb
There may have been a previous request that timed out before the client was able to read the response. In that case, the response will still be sitting in the socket waiting to be read. If the response we just read was to a previous request, we can safely skip it.
> Skip responses to previous requests

- lib/kafka/broker_pool.rb
- lib/kafka/producer.rb
- spec/functional/producer_spec.rb
- spec/producer_spec.rb
Rather than having BrokerPool handle connection retries we should consolidate that logic in Producer in order to avoid nested retry loops. Furthermore, by moving connection error handling into the existing Producer retry loop we can more intelligently control when to refresh the cluster metadata. This is now done when some response errors are encountered, as well.
> Consolidate metadata refresh policy

- lib/kafka/producer.rb
- lib/kafka/transmission.rb
Transmission is responsible for sending buffered messages to the brokers in a cluster. There's no retry logic – that stuff is still handled by Producer.
Downside: the mutable MessageBuffer will be shared between Producer and Transmission. Part of the response handling is marking messages as sent in the buffer, so it's hard to avoid.
I'm not quite sure about the name. The idea is to represent a single pass at transmitting messages to the cluster, but I'm not sure if we should instead use something closer to "send", e.g. MessageSender... but that sounds pretty horrible...
> Extract transmission logic from Producer

- lib/kafka/connection.rb
- lib/kafka/socket_with_timeout.rb
- spec/socket_with_timeout_spec.rb
`Socket.tcp` with a connection timeout value yields horrible performance. Replacing it with a non-blocking socket and `IO.select` improves latency by an order of magnitude.
In addition to this, network timeout related code is now centralized in SocketWithTimeout.
> Use low-lever socket timeouts

- lib/kafka/connection.rb
- lib/kafka/protocol/decoder.rb
- lib/kafka/socket_with_timeout.rb
- spec/connection_spec.rb
- spec/socket_with_timeout_spec.rb
We ran into an issue in our staging environment where network connection errors caused `Errno::EPIPE` to be raised from `Socket#read`. This was not handled gracefully, and the error propagated up through the stack.
This PR contains a few fixes:
* Before, socket timeouts were not being properly set. This was discovered during testing.
* Sockets can no longer get into a bad state. Rather, if they raise an exception they're closed and discarded, and a new one will be opened the next time a connection is used.
* Gracefully handle unexpectedly reaching the end of a buffer when reading a response.
> Handle flaky network conditions

- lib/kafka/broker.rb
- lib/kafka/protocol/metadata_response.rb
- spec/broker_pool_spec.rb
There's no need to raise an error unless the client actually tries to use the topic/partition.
Fixes #55.
> Don't raise topic/partition errors when fetching metadata

- examples/simple-consumer.rb
- examples/simple-producer.rb
- lib/kafka/broker.rb
- lib/kafka/client.rb
- lib/kafka/fetched_message.rb
- lib/kafka/protocol.rb
- lib/kafka/protocol/decoder.rb
- lib/kafka/protocol/fetch_request.rb
- lib/kafka/protocol/fetch_response.rb
- lib/kafka/protocol/list_offset_request.rb
- lib/kafka/protocol/list_offset_response.rb
- lib/kafka/protocol/message.rb
- lib/kafka/protocol/message_set.rb
- spec/broker_spec.rb
- spec/functional/producer_spec.rb
Implements #47.
Fetches a batch of messages from a specified partition.
> Allow fetching messages from a specific partition

- lib/kafka/client.rb
- lib/kafka/fetch_operation.rb
- lib/kafka/protocol/list_offset_response.rb
Extracts FetchOperation from Client and makes the code more generic. This is necessary for fetching messages from more than one partition at a time, which will be required for the Consumer API.
> Extract FetchOperation

- lib/kafka/message_buffer.rb
- lib/kafka/produce_operation.rb
Subscribers can track writes to individual partitions. This allows monitoring throughput per topic and partition.
> Instrument writes to topic partitions

- lib/kafka/broker_pool.rb
- lib/kafka/producer.rb
- spec/producer_spec.rb
* Limit the response size by only requesting metadata for topics that we buffered have messages for.
* By setting the topics in the metadata request Kafka will automatically create them if `auto.create.topics.enable` is enabled in the Kafka brokers.
The producer adds the topics with buffered messages to the broker pool's list of target topics. The broker pool takes care of re-fetching metadata when needed.
Should fix #62.
> Explicitly set the topics to get metadata from

- lib/kafka/broker_pool.rb
- lib/kafka/message_buffer.rb
- lib/kafka/pending_message.rb
- lib/kafka/producer.rb
- lib/kafka/protocol/metadata_response.rb
- spec/producer_spec.rb
Until now, `Producer#produce` has required access to the cluster metadata in order to determine the partition that a given message should be assigned to. In the case of Kafka being unavailable, this would have blocked clients from buffering messages, as the metadata request would fail. Furthermore, since ffc1a34 the metadata has been invalidated the first time `#produce` is called with a topic not seen by the Producer instance before. This would mean a thundering herd of metadata requests when e.g. a cluster of web application processes are restarted. By postponing the metadata request until we're ready to send all the messages, we'll be able to do a single request containing *all* the topics.
This is done by adding a separate first-stage buffer to Producer. This is a flat list of pending …
> Allow buffering messages even when Kafka is unavailable

- lib/kafka/broker_pool.rb
- lib/kafka/partitioner.rb
- lib/kafka/produce_operation.rb
- lib/kafka/producer.rb
- spec/functional/producer_spec.rb
An error in `add_target_topics` caused new topics to not be added to the target list. Furthermore, the LeaderNotAvailable exception raised when attempting to send messages to a newly created topic was not being handled.
Should fix #62 for real this time.
> Fix automatic topic creation

- spec/functional/producer_fuzz_spec.rb
- spec/spec_helper.rb
This test tries to produce a million messages to a Kafka cluster that is simultaneously being screwed with by a separate thread that randomly kills of of the nodes, waits 30 seconds, restarts the node, waits another 30 seconds, and repeats.
Hopefully this will flush out hard-to-find bugs.
> Add a fuzz test

- lib/kafka/fetch_operation.rb
- spec/functional/fetch_spec.rb
- spec/functional/producer_spec.rb
By adding the target topic to the broker pool, subsequent metadata requests will ensure that the topic is created.
Fixes #71.
> Allow automatically creating topics when fetching messages

- lib/kafka/broker_pool.rb
- lib/kafka/fetch_operation.rb
- lib/kafka/producer.rb
- spec/broker_pool_spec.rb
- spec/functional/fetch_spec.rb
- spec/producer_spec.rb
Previously, `BrokerPool#mark_as_stale!` would cause the cached metadata to be removed, but each subsequent call for metadata info (such as leader lookups) would cause a metadata request. In order to avoid this situation, the metadata is kept in the cache even though it's stale. This makes sense because the metadata is not either completely accurate or completely inaccurate -- it can be accurate for some partitions but not others. Therefore we get as much work done as possible with the existing metadata and only do a refresh when we start a new retry.
> Avoid a barrage of metadata requests on errors

- lib/kafka/broker_pool.rb
- lib/kafka/client.rb
- lib/kafka/cluster.rb
- lib/kafka/fetch_operation.rb
- lib/kafka/produce_operation.rb
- lib/kafka/producer.rb
- spec/cluster_spec.rb
- spec/producer_spec.rb
Extracts the cluster-specific parts of BrokerPool to Cluster, leaving only broker pool handling.
> Introduce Cluster, limit the responsibility of BrokerPool

- lib/kafka/broker.rb
- lib/kafka/connection.rb
- lib/kafka/protocol/fetch_request.rb
- lib/kafka/protocol/list_offset_request.rb
- lib/kafka/protocol/produce_request.rb
- lib/kafka/protocol/topic_metadata_request.rb
- spec/broker_spec.rb
- spec/connection_spec.rb
Currently, Broker is responsible for orchestrating requests by combining a request class and a response class for a given logical API call. Sometimes a response isn't expected (e.g. for produce API calls with `required_acks=0`) and this case must be handled.
It makes more sense to me to have the individual request classes handle these decisions. Broker is now just an easier-to-use wrapper around the concrete request classes.
> Let the request class define the response class

- README.md
- examples/simple-producer.rb
- lib/kafka/producer.rb
- spec/functional/producer_spec.rb
- spec/fuzz/producer_spec.rb
- spec/producer_spec.rb
I feel that "send" doesn't capture what's happening: the producer may "send" multiple requests, but it's all part of a single attempt at "delivering" the buffered messages.
This is a breaking API change, but at this point in ruby-kafka's development I'm not too worried about that. I want to have a nice API once we reach 1.0.
I'm also thinking about renaming `Producer#produce`, although I'm not sure what would be better. I'm afraid people will think `#produce` actually delivers the message...
> Rename Producer#send_messages to #deliver_messages

- lib/kafka/async_producer.rb
- lib/kafka/client.rb
- spec/async_producer_spec.rb
- spec/functional/async_producer_spec.rb
- spec/functional/producer_spec.rb
Adds an async producer with options for automatic delivery:
* at a fixed time interval; and
* when the producer buffer reaches a configured threshold.
Closes #10.
> Implement an async producer

- lib/kafka/produce_operation.rb
- lib/kafka/producer.rb
- lib/kafka/protocol/message_set.rb
- spec/protocol/message_set_spec.rb
In our use case we have a single producer that writes to dozens of topics, with an uneven throughput distribution. This means that it would make sense to enable compression for some topics and not others. On the other hand, our writes sometimes spike on some topics.
Rather than decide up front which topics should have compression enabled and which should not, this API would allow the user to set a threshold defined in terms of the number of messages buffered for a single partition. Only if the threshold is reached are the messages compressed.
> Allow specifying a compression threshold

- lib/kafka/message_buffer.rb
- lib/kafka/pending_message.rb
- lib/kafka/pending_message_queue.rb
- lib/kafka/producer.rb
- lib/kafka/protocol/message.rb
- spec/message_buffer_spec.rb
Since buffer size limits are mainly in place in order to avoid unbounded memory growth, defining the limits in terms of memory size makes sense. However, this does introduce some complexity – this is an attempt to see if it's worth the trouble.
> Allow specifying buffer limits in terms of byte size

- lib/kafka.rb
- lib/kafka/broker.rb
- lib/kafka/client.rb
- lib/kafka/cluster.rb
- lib/kafka/connection.rb
- lib/kafka/consumer.rb
- lib/kafka/consumer_group.rb
- lib/kafka/fetch_operation.rb
- lib/kafka/protocol.rb
- lib/kafka/protocol/consumer_group_protocol.rb
- lib/kafka/protocol/group_coordinator_request.rb
- lib/kafka/protocol/group_coordinator_response.rb
- lib/kafka/protocol/group_protocol.rb
- lib/kafka/protocol/heartbeat_request.rb
- lib/kafka/protocol/heartbeat_response.rb
- lib/kafka/protocol/join_group_request.rb
- lib/kafka/protocol/join_group_response.rb
- lib/kafka/protocol/leave_group_request.rb
- lib/kafka/protocol/leave_group_response.rb
- lib/kafka/protocol/member_assignment.rb
- lib/kafka/protocol/offset_commit_request.rb
- lib/kafka/protocol/offset_commit_response.rb
- lib/kafka/protocol/offset_fetch_request.rb
- lib/kafka/protocol/offset_fetch_response.rb
- lib/kafka/protocol/sync_group_request.rb
- lib/kafka/protocol/sync_group_response.rb
- spec/functional/consumer_group_spec.rb
This is still very _very_ alpha level.
The consumer group API is very generic and therefore somewhat hard to grok. It's basically a general-purpose coordination API, with the consumer group API being a sub-protocol. The clients themselves are responsible for assigning partitions among themselves; one is selected as the leader for a specific generation and sends a list of member -> partitions assignments to the Kafka broker. This allows the clients to control assignment policies, but also makes it a bit more upfront work.
> Implement Consumer Group API

- lib/kafka/consumer.rb
- lib/kafka/consumer_group.rb
- lib/kafka/offset_manager.rb
- spec/fuzz/consumer_group_spec.rb
Automatically commits offsets every ten seconds. Another PR will make this configurable and probably add the option of expressing the commit frequency in terms of the number of messages processed.
Also fixed an issue that caused lots of duplicate processing: when an error code from the cluster caused a group re-join, we didn't reset the current message loop. Now such errors propagate to the loop, causing it to break and re-start with a new batch.
> Automatically commit offsets at fixed intervals

- lib/kafka/client.rb
- lib/kafka/offset_manager.rb
The threshold represents the number of messages that can be processed before an offset commit is required, thus putting an upper bound on duplicate message processing in case a consumer dies.
> Allow specifying the offset commit policy as a threshold

- README.md
- examples/ssl-producer.rb
- lib/kafka/broker_pool.rb
- lib/kafka/client.rb
- lib/kafka/connection.rb
- lib/kafka/ssl_socket_with_timeout.rb
- spec/ssl_socket_with_timeout_spec.rb
This lets this client support ssl connections. I was relatively unsure of how to add tests for this, but have a staging environment setup with SSL support, so I've tested a number of failure scenarios and such.
This implements https://github.com/zendesk/ruby-kafka/issues/100.
Ruby SSL socket support is a nightmare, and actually impossible to use to do timeouts "correctly". I've left a lot of comments in the SSLSocketWithTimeout class to that effect.
> SSL connection support

- README.md
- lib/kafka/broker_pool.rb
- lib/kafka/client.rb
- lib/kafka/connection.rb
- lib/kafka/ssl_socket_with_timeout.rb
- spec/ssl_socket_with_timeout_spec.rb
instead of forcing the user to construct the SSL cert, take the most
common options and create an SSLContext from them.
This sidesteps a lot of potential security worries, and means our users don't need to read the docs for `SSLContext`.
> cleaner SSL interface

- lib/kafka/consumer.rb
* Send a heartbeat after half the session timeout has expired in order to avoid getting kicked out of the group if the heartbeat request is delayed a bit.
* Send the first heartbeat only after the heartbeat interval has expired rather than immediately.
> Simplify the heartbeat algorithm

- README.md
- examples/firehose-consumer.rb
- lib/kafka/consumer.rb
- spec/functional/consumer_group_spec.rb
The consumer now automatically leaves the group when the `each_message` loop is broken. I may re-introduce `shutdown` with different semantics later in order to improve controlled shutdowns, e.g. a signal trap.
> Remove the `shutdown` method from Consumer

- lib/kafka/protocol/decoder.rb
The Kafka API docs say:
> As an optimization the server is allowed to return a partial message
> at the end of the message set. Clients should handle this case.
https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-FetchAPI
Since the message declares the number of bytes to read it's possible to
ensure that many bytes were read from the socket. If there's a mismatch
then do not process those bytes as a response.
Fixes #133
> Discard partial responses from Kafka

- lib/kafka/compressor.rb
- lib/kafka/protocol/message.rb
In anticipation of KIP-32, which starts using the 4th lowest attribute bit.
> Only use the three lowest attribute bits for the codec id

- lib/kafka/message_buffer.rb
- lib/kafka/pending_message.rb
- lib/kafka/produce_operation.rb
- lib/kafka/producer.rb
- lib/kafka/protocol/message.rb
Write down the time a message was produced and include timing information in the message ack notifications. This will also fit well with [KIP-32](https://cwiki.apache.org/confluence/display/KAFKA/KIP-32+-+Add+timestamps+to+Kafka+message) once we switch to Kafka 0.10 APIs in the future.
My main concern is the switch to instrumenting individual message acks – when buffering e.g. 1,000 messages and delivering them at once, the cost of instrumentation could stack up...
> Track message delivery delays

- lib/kafka/client.rb
- lib/kafka/consumer.rb
- lib/kafka/fetch_operation.rb
- lib/kafka/fetched_batch.rb
- spec/functional/batch_consumer_spec.rb
- spec/functional/consumer_group_spec.rb
This API allows consumers to work on entire _batches_ of messages, where a _batch_ is a continuous set of messages from the same topic/partition. The use cases for typically revolve around wanting to amortize the cost of writing messages to an external store.
This is the proposed API:
```ruby
consumer = kafka.consumer(group_id: "my-group")
consumer.each_batch do |batch|
txn = SomeStore::Transaction.new
batch.messages.each {|message| txn.add(message.value) }
txn.commit
end
```
Each message batch is yielded to the provided block; after the block returns, a heartbeat is sent to the group coordinator and perhaps the offset of the partition is committed (depending on configuration). This means that
1. The block should not spend more time than `session_timeout`, or the consumer will be kicked …
> Batch oriented consumer API

- lib/kafka/client.rb
- lib/kafka/consumer.rb
- lib/kafka/heartbeat.rb
Allows configuring the consumer heartbeat interval. By default it's set to 10 seconds, which should be reasonable given the default session window size of 30 seconds.
```ruby
consumer = kafka.consumer(
heartbeat_interval: 5, # send a heartbeat every five seconds
)
```
> Make consumer heartbeat frequency configurable

- lib/kafka/instrumenter.rb
For example, this point doesn't pass block: https://github.com/zendesk/ruby-kafka/blob/7ffcf2c953b3560014c9312533e6a7eed8663fb4/lib/kafka/producer.rb#L207
> Need nil check for block because some points don't pass block

- lib/kafka/consumer.rb
- lib/kafka/fetched_batch.rb
By setting `min_bytes` and `max_wait_time` a consumer can trade off batch size and latency:
* `max_wait_time` is the maximum number of seconds the broker will wait before returning data to the client, effectively a bound on latency. A higher value allows for bigger batches.
* `min_bytes` specifies the minimum number of bytes a broker should wait for before returning data to the client. Ignored after `max_wait_time` is reached.
Note that both options are per broker, so when fetching from multiple brokers (as would be typical) the parameters would apply to individual client-broker requests, not to the overall fetch.
> Allow configuring fetch parameters when consuming messages

- lib/kafka/producer.rb
required_acks 0 means the producer never waits acks from the brokers.
Previous code causes duplicated messages because buffer isn't updated
by producer opertaions with required_acks 0
> Producer should not retry when required_acks is 0

- lib/kafka/produce_operation.rb
- spec/producer_spec.rb
This change will make the producer send notifications whenever a) it's not possible to find the leader of a partition or b) there's an error for a partition in a produce response. Clients can subscribe to these notifications in order to implement error monitoring.
> Instrument errors in the producer

- lib/kafka/round_robin_assignment_strategy.rb
Although an edge case, the resulting error is understandable compared to: TypeError: no implicit conversion of nil into Array.
> Prevent TypeError in favor of user friendly "No partitions assigned!"

- lib/kafka/pending_message_queue.rb
- lib/kafka/producer.rb
Before, a topic error would stop messages for other topics from being assigned to a partition and therefore from being delivered. In order to better isolate topic errors, this change goes through all pending messages and writes those without errors to the produce operation buffer, leaving the rest in the pending message queue.
> Continue assigning partitions when there's an error

- lib/kafka/produce_operation.rb
- lib/kafka/producer.rb
- spec/producer_spec.rb
Currently, there's no direct way of tracking the errors encountered when assigning partitions to messages. Furthermore, the partition error instrument is confusing and too granular.
> Instrument topic errors

- lib/kafka/offset_manager.rb
After committing offsets, the consumer would clear the information of which offsets had been processed but fail to refresh the broker supplied table, leading to erroneous offset information.
Should fix #173.
~~This means that whenever we commit offsets, we also fetch the updated offset table, which is obviously inefficient. I'll try to improve performance soon.~~ Added a commit that only clears the necessary info, since the other caches are cleared whenever the consumer re-joins the group.
> Don't use stale offset information when consuming messages

- lib/kafka/consumer.rb
- lib/kafka/round_robin_assignment_strategy.rb
- spec/functional/async_producer_spec.rb
- spec/functional/batch_consumer_spec.rb
- spec/functional/client_spec.rb
- spec/functional/compression_spec.rb
- spec/functional/consumer_group_spec.rb
- spec/functional/producer_spec.rb
- spec/spec_helper.rb
- spec/test_cluster.rb
Rather than re-using the same topic across examples we now create topics on demand. This change flushed out a few errors related to partitions not having a leader, which were fixed at the same time.
> Refactor functional specs & improve resilience

- lib/kafka/consumer.rb
- avoids redundant commiting and double processing on crash
> mark the just processed message before commit offset

- lib/kafka/async_producer.rb
- spec/async_producer_spec.rb
We shouldn't crash the application when that happens. Closes #184.
> Handle connection errors in the async producer

- lib/kafka/message_buffer.rb
- spec/message_buffer_spec.rb
For some reason, `#concat` is sometimes called with an empty array. This caused the code to blow up.
Fixes #188.
> Handle message buffer edge case

- lib/kafka/produce_operation.rb
After a rebalance the producer fails to send the messages
with 'Unknown topic or partition' error.
By forcing a cluster metadata refresh after rescuing this error the
producer adapts to the new cluster state and continues to send
the messages normally.
I reproduce the problem with the following steps:
I run the following producer script: 
```
require "kafka"
kafka = Kafka.new(seed_brokers: ["kafka.vm.skroutz.gr:9092", "kafka-b.vm.skroutz.gr:9092"], 
logger: Logger.new(STDOUT))
producer = kafka.async_producer(delivery_interval: 10)
while true
producer.produce("hello", topic: "skroutz.test")
sleep 5
end
```
Cluster state before rebalance:
Logger output before rebalance:
```
D, [2016-05-26T15:28:58.379706 #11682] DEBUG -- : Current leader for skroutz.test/1 is node kafka-c.vm.skroutz.gr:9092 …
```
> Handle rebalances in the producer

- README.md
- lib/kafka/consumer.rb
Implements #207.
The new API will be:
```ruby
consumer.subscribe("stats", start_from_beginning: false) # default is true
```
> Simplify the API for setting subscription starting points

- lib/kafka/client.rb
- lib/kafka/cluster.rb
- spec/cluster_spec.rb
With the previous normalization/parsing process it was impossible
to use IPv6 addresses directly in the seed_brokers array/string.
This commit enables the client to accept IPv6 addresses with port
in the following URI-like format:
`[2a00:1450:400d:802::200e]:9092`
> Accept IPv6 addresses for seed_brokers

- lib/kafka/datadog.rb
- ruby-kafka.gemspec
Metrics will be reported using Datadog's modified Statsd client.
This reporter is specific to [Datadog](https://www.datadoghq.com/), but other reporters can easily be added.
> Add a Datadog metrics reporter

- lib/kafka/pending_message.rb
- lib/kafka/producer.rb
Now I'm working on replacing poseidon with ruby-kafka in fluent-plugin-kafka.
I checked the performance and I found PendingMessage initialization consumes CPU because Producer#produce is called frequently.
I tested simple benchmark and it shows class with keyword argument is slower.
So using struct is better for `PendingMessage` usecase.
- Benchmark code:
```rb
require 'benchmark'
class PendingMessage1
attr_reader :value, :key, :topic, :partition, :partition_key
attr_reader :bytesize, :create_time
def initialize(value:, key:, topic:, partition:, partition_key:, create_time:)
@key = key
@value = value
@topic = topic
@partition = partition
@partition_key = partition_key
@create_time = create_time
@bytesize = key.to_s.bytesize + value.to_s.bytesize
end
end
class PendingMessage2
attr_reader …
```
> PendingMessage: Use struct instead of class to improve performance

- lib/kafka/client.rb
- lib/kafka/compressor.rb
- spec/functional/client_spec.rb
This is simple API that offers neither performance nor fault tolerance, making it ideal for Ruby! More seriously, it addresses a very specific scenario: sending one-off messages. Currently, you have to be careful to avoid leaving messages in a Producer buffer when something goes wrong, and setting up a producer in the first place when all you want is something hammer-shaped that sends a message to Kafka is something you'd expect from a Java library.
The API looks like this:
```ruby
kafka = Kafka.new(...)
kafka.deliver_message("hello, world!", topic: "greetings")
```
The API doesn't allow enabling compression, nor does it allow configuring the `required_acks` or `ack_timeout` parameters.
> Add a simple API for synchronously sending a single message

- lib/kafka/client.rb
- lib/kafka/fetched_batch.rb
- spec/functional/client_spec.rb
The API is extremely simple, but also lacks flexibility:
```ruby
kafka = Kafka.new(...)
kafka.each_message(topic: "greetings") do |message|
puts message.value
end
```
This will be fine for simple use cases, but of course won't suffice when e.g. checkpointing or distribution is required.
> Add an experimental simplified consumer API

- lib/kafka/consumer_group.rb
Some exceptions, e.g. RequestTimedOut, were not being handled. Opting for a catch-all rescue instead.
> Simplify the offset commit error handling

- lib/kafka/client.rb
After the release of v0.3.9 every kafka client tries to parse seed
brokers using URI which is not required by default without bundler.
This patch explicitly requires uri and allows the kafka client
to work without bundler.
Fixes #223
> Require uri in case of running without bundler

- lib/kafka/client.rb
- lib/kafka/cluster.rb
- lib/kafka/offset_manager.rb
Previously, the first time a partition was consumed there would be no committed offset, so the consumer would use the default offset (either the earliest or the latest offset in the partition.) However, the actual offset number would only be resolved when the consumer fetched from the partition. This would leave a race condition when a consumer subscribes to the latest messages for a topic: if no messages arrive while the fetch is waiting, no offset will be committed; in the next iteration, the offset will be resolved anew, but that means skipping any message that has arrived in the meantime. Only when messages arrive *while* the consumer is doing a fetch on a partition will this race be broken.
The new behavior is to resolve the default offset as soon as possible and to commit the actual …
> Eagerly resolve default offsets in the consumer

- lib/kafka/consumer.rb
There's no reason to rejoin the group when a fetch fails, it's most likely due to network errors or partition leadership changes.
Should fix #226.
> Mark the cluster as stale on fetch error

- lib/kafka/cluster.rb
- lib/kafka/fetch_operation.rb
- lib/kafka/offset_manager.rb
Before, we would commit offsets that were out of range in the partition.
> Stop trying to commit offsets that are out of range

- lib/kafka/client.rb
- lib/kafka/cluster.rb
- spec/functional/client_spec.rb
Previously, if the client had add a set of topics to its internal list, only those topics would be returned.
Fixes #234.
> Return all topics from Client#topics

- lib/kafka/client.rb
- spec/functional/client_spec.rb
Add a simple API for fetching the offset of the last message in a partition:
```ruby
kafka.last_offset_for("some-topic", 42) #=> 123
```
I may want to change the API such that the partition is specified with a keyword parameter, e.g. `partition: 42`. This would allow extending the API to support multiple partitions, e.g. `partitions: [42, 42]`.
Closes #225.
> Add an API for retrieving the last offset in a partition

- examples/simple-consumer.rb
- lib/kafka/client.rb
- lib/kafka/fetched_batch.rb
The simple consumer repeatedly consumed the last message in a partition.
> Only consume the last message once

- lib/kafka/connection.rb
- lib/kafka/socket_with_timeout.rb
- lib/kafka/ssl_socket_with_timeout.rb
Connection errors were being raised when Kafka had killed an idle client connection. Rather than just raising an exception, we should try to reconnect if we can see that the connection has been closed.
> Don't consider the socket open if it's closed (duh!)

- lib/kafka/connection.rb
Kafka brokers automatically close client connections that have been inactive for a while. If the client then tries to use the connection, a network error will be raised. In order to avoid polluting logs and monitoring systems with these errors, we can retry requests.
> Retry requests when the broker closes the connection

- lib/kafka/consumer.rb
- lib/kafka/offset_manager.rb
* Commit offsets even when no messages are being processed. Before, the consumer would not commit pending offsets until a new message was processed.
* Wait for the configured amount of time before first committing offsets.
> Improve consumer offset commit code

- lib/kafka/async_producer.rb
The shutdown method used to terminate only the Worker thread and not
the Timer thread. The Timer thread continues to push `deliver_messages`
to the queue but the Worker thread is not alive to consume them.
After some time the queue fills with `deliver_messages` and the next
try to produce a message fails with `Kafka::BufferOverflow`.
This commit fixes the issue by terminating the Timer thread
together with the Worker thread on shutdown.
Code to reproduce:
```
require "kafka"
kafka = Kafka.new(seed_brokers: ['kafka.vm.skroutz.gr:9092',
'kafka-b.vm.skroutz.gr:9092',
'kafka-c.vm.skroutz.gr:9092'],
logger: Logger.new(STDOUT))
producer = kafka.async_producer(delivery_interval: 1, max_queue_size: 10) 
at_exit { producer.shutdown }
producer.produce("test1", topic: "skroutz.scratch.v1") …
```
> Fix invalid BufferOverflow error in AsyncProducer

- lib/kafka/consumer.rb
- lib/kafka/consumer_group.rb
- lib/kafka/offset_manager.rb
- spec/functional/consumer_group_spec.rb
- spec/offset_manager_spec.rb
When a group resyncs we were discarding all local data about which partition offsets had been processed. Any data that had not been committed would be lost, even if the consumer was assigned some of the same partitions after the sync. With this change, consumers only discard offset data for partitions they are no longer assigned.
This should result in less reprocessing of messages. Running the consumer group fuzz test indeed indicates that this is the case, with the number of duplicates going from upwards of 10% to about 0.1%
> Don't discard all consumer offset data on resync

- lib/kafka/connection.rb
EHOSTUNREACH is raised when we try to connect to a turned off broker.
We should rescue this error in order to mark cluster as stale and fetch
the metadata of the new cluster state without this broker.
> Rescue EHOSTUNREACH in case of turned off broker

- lib/kafka/cluster.rb
- lib/kafka/offset_manager.rb
- spec/offset_manager_spec.rb
We've run into problems when a consumer is assigned a _lot_ of partitions – since the current code resolves the starting position for each partition in a separate Kafka API call, the consumer would exceed the session timeout doing those calls before being able to do any work. Since it would be kicked out of the group before being ready to commit those offsets, it would have to start over, causing an infinite loop of ListOffsets calls.
This change makes each consumer execute the minimum number of API calls to resolve the starting position for _all_ partitions in a given topic. It's possible to further optimize by having just a single call to each broker that queries across all topics, but that would complicate matters further right now.
> Avoid calling the ListOffsets Kafka API for each assigned partition

- lib/kafka/consumer_group.rb
We've seen this pop up in production. Setting to nil seems to cause issues.
> Reset member id when not known by coordinator

- lib/kafka.rb
- lib/kafka/consumer.rb
- lib/kafka/fetch_operation.rb
- lib/kafka/offset_manager.rb
If the committed offset for a given partition is invalid, there's not much to do except resetting to the default offset.
This could be a horrible idea. I need to do some more research in order to verify that commits can in fact become corrupted and it's not just ruby-kafka messing up right now.
> Reset the consumer's position when an offset is out of range

- lib/kafka/consumer.rb
- lib/kafka/fetched_batch.rb
- spec/consumer_spec.rb
Currently, there's no good way of knowing which message caused a consumer to crash with an exception. This change adds logging of the specific location (topic, partition, offset) as well as the full stack trace of the exception.
> Log message location when user code raises an exception

- lib/kafka/offset_manager.rb
We've seen cases where the consumer crashed because it was trying to look up the resolved offset for a partition that was not in the memoized hash. I believe this happened because:
1. The consumer initially gets a hash of resolved default offsets for a given topic;
2. there's a rebalance and the consumer gets assigned at least one new partition in the topic;
3. it needs to look up the resolved default offset for that partition, but it's not in the – because it's still memoized.
The solution is to clear the memoized values every time there's a rejoin.
> Clear resolved offsets on group rejoins

- lib/kafka.rb
- lib/kafka/consumer.rb
- spec/consumer_spec.rb
In some cases, a specific message with e.g. a malformed payload will cause a consumer's message processor to raise an exception, e.g.
```ruby
consumer.each_message do |message|
value = JSON.parse(message.value) # <-- this could fail!
...
end
```
There are myriad other ways a processor could fail, and oftentimes the cause will be deterministic and based on a single message containing something unexpected.
For this reason, the official Java client allows [pausing specific partitions](https://kafka.apache.org/090/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#pause(org.apache.kafka.common.TopicPartition...)), making the consumer skip them when fetching messages. An operator would typically have to look into the matter, fix the underlying issues, and resume processing. In the …
> Allow pausing partitions in the consumer

- Gemfile.lock
- lib/kafka/consumer.rb
- ruby-kafka.gemspec
- spec/consumer_spec.rb
Although pausing a partition is a good way to avoid a single message causing a complete crash of a consumer, it may sometimes make sense to retry processing of the message, even if the user hasn't gone in and deployed a code change to handle the error, as sometimes the exception is due to an external resource referenced by the message that's in a temporary error state.
This change allows pausing a partition while setting a timeout for the pause. After the timeout expires, the partition is resumed.
> Allow setting a timeout on a partition pause

- lib/kafka/consumer_group.rb
It is possible for a group coordinator after a group rebalance to send
a group to another group coordinator. This results in NotCoordinatorForGroup
error in the next heartbeat attempt and the consumer crashes.
This commit gracefully handles this problem by getting the new group
coordinator from the cluster and retrying the heartbeat.
> Rescue NotCoordinatorForGroup during heartbeats

- lib/kafka/offset_manager.rb
- spec/offset_manager_spec.rb
This PR fixes issue #280 
@dasch I tried to follow your recommendation to move +1 to `commit _offsets` but `offset_manager#next_offset_for` is involved in two scenarios:
1) When `@processed_offsets` is not initialized and it reads from kafka
2) While the batch is not committed, thus depending on `@processed_offsets` to get the next offset
+1 is in `offset_manager#mark_as_processed` now to keep all the logic inside the offset manager.
> Ensures that kafka has the offset off the next message

- README.md
I believe the change in 3bdd25ea9fbfd7e0305eae3a0292413534e8a0cc
made inclusion ordering not required, as it moved away from
the singleton.
Having read the code, as well as tested with the following simple
example, I believe this to be the case:
```ruby
require "kafka"
require "active_support/notifications"
ActiveSupport::Notifications.subscribe(/.*\.kafka$/) do |*args|
event = ActiveSupport::Notifications::Event.new(*args)
puts "Received notification `#{event.name}` with payload: #{event.payload.inspect}"
end
instrumenter = Kafka::Instrumenter.new(client_id: "test")
instrumenter.instrument("test_event", foo: :bar) { 1 + 1 }
```
I suppose if you have gem requirements staggered after Kafka
consumers/producers are initialized, this may still be good advice.
> Remove Instrumentation readme ordering bit

- lib/kafka/client.rb
.prepend is destructive.  fails on frozen strings.
> don't modify incoming seed_brokers strings

- lib/kafka/client.rb
I have a client key that is DSA encoded, and I kept getting this error:
```
/usr/local/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.3.8/lib/kafka/client.rb:304:in `initialize': Neither PUB key nor PRIV key: nested asn1 error (OpenSSL::PKey::RSAError)
from /usr/local/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.3.8/lib/kafka/client.rb:304:in `new'
from /usr/local/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.3.8/lib/kafka/client.rb:304:in `build_ssl_context'
from /usr/local/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.3.8/lib/kafka/client.rb:48:in `initialize'
from /usr/local/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.3.8/lib/kafka.rb:136:in `new'
from /usr/local/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.3.8/lib/kafka.rb:136:in `new'
from example.rb:16:in `<main>'
```
The OpenSSL docs indicate that [this …
> Detect private key type (instead of always using RSA)

- lib/kafka/consumer.rb
- lib/kafka/consumer_group.rb
- spec/consumer_spec.rb
We ran into an issue where a ConsumerGroup was assigned partitions for a topic that the Consumer was not subscribed to. This was a topic that the consumer group used to consume, but that we were no longer using.
This led to an exception in the OffsetManager because there was no default offset for the topic that the consumer no longer subscribes to: https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/offset_manager.rb#L104
The proposed fix here addresses the issue by only fetching from partitions for the topics that the consumer is subscribed to.
I tried to write a functional test for the ConsumerGroup to demonstrate the problem, but was unable to reproduce it using the test cluster.
> Only fetch messages for subscribed topics

- lib/kafka/client.rb
- lib/kafka/consumer_group.rb
- spec/functional/batch_consumer_spec.rb
- spec/functional/consumer_group_spec.rb
- spec/fuzz/consumer_group_spec.rb
This change implements a version of the enhancement described in https://github.com/zendesk/ruby-kafka/issues/233.
Our use case for this is a very low throughput topic where some partitions do not receive new messages within the broker's retention period setting (1 day). Previously committed offsets would be purged and the next day the partition would be read from the beginning again.
Exposing this setting to the consumer provides more flexibility than changing the broker's setting for all consumers.
> Expose offset retention time in the Consumer API

- CHANGELOG.md
- README.md
- lib/kafka/client.rb
- lib/kafka/offset_manager.rb
- spec/offset_manager_spec.rb
This change addresses Issue https://github.com/zendesk/ruby-kafka/issues/317.
Previously committed offsets are re-committed at the first commit and periodically after that at an interval that is half the _offset retention time_. If the _offset retention time_ is not specified for the consumer, then half of the broker's default setting (1 day) is used.
> Periodically re-commit previously committed offsets

- lib/kafka/client.rb
`ssl_ca_cert` adds a single certificate to the OpenSSL:X509::Store, but some configurations have longer certificate chains than just one level.
This commit exposes`add_file` of OpenSSL:X509::Store to allow adding all certificates contained in a file.
> Allow ssl_ca_cert to be an array of PEM encoded certificates

- lib/kafka/message_buffer.rb
When @buffer[topic][partition].count was zero a "TypeError nil can't be coerced into Fixnum" was thrown
because [].reduce(:+) returns nil (line 59)
and Fixnum - nil raises this error
> Fix TypeError nil can't be coerced into Fixnum

- lib/kafka/cluster.rb
Yesterday, a component of ours had vastly increased latency during an
outage, to the point where callers were timing out and seeing issues.
Upon tracking this down, we found that the cause of the latency was that
broker 0 was replaced. This component uses the sync producer, and as a
result of broker 0 being replaced, any produce request that fetched
metadata stalled for the default connect timeout (10s).
Instead, fetch metadata from seed brokers in a random order. This means
that a single broker going down will slow down at most 1/NBROKERS
metadata fetches, rather than every single one.
> shuffle seed brokers before fetching metadata

- lib/kafka/consumer.rb
- spec/consumer_spec.rb
It turns out it's a pretty common situation when we get `ConnectionError` right after we stopped consumer.
Retrying offsets commitment allows us to make sure it is commited properly to avoid situation when large batch of messages will be processed again after consumer's restart.
> Retry final offsets commit if timed out

- lib/kafka/client.rb
- lib/kafka/consumer.rb
- lib/kafka/offset_manager.rb
- spec/consumer_spec.rb
- spec/offset_manager_spec.rb
This PR exposes `#commit_offsets` on Consumer and adds an option to avoid auto commit offsets on `#each_batch`
> Allow committing offsets manually 

- lib/kafka/consumer.rb
- spec/consumer_spec.rb
This is a follow up to https://github.com/zendesk/ruby-kafka/pull/342
* Exposes `#commit_offsets` and `#automatically_mark_as_processed ` on Consumer
* It adds `automatically_mark_as_processed` option to `#each_batch` and `#each_message`.
> Add auto commit option to each batch 

- README.md
- lib/kafka/consumer.rb
Improves the documentation of https://github.com/zendesk/ruby-kafka/pull/344 and expands the use to also include `#each_message`.
> Improve `automatically_mark_as_processed`

- lib/kafka.rb
- lib/kafka/consumer.rb
* Raise a more meaningfull error when no partitions are
assigned
This small change is to make easier/cleaner handling this error on the client side.
> Add NoPartitionsAssignedError

- lib/kafka/broker.rb
- lib/kafka/connection.rb
- lib/kafka/consumer.rb
- lib/kafka/fetch_operation.rb
- lib/kafka/instrumenter.rb
- lib/kafka/protocol/null_response.rb
- spec/connection_spec.rb
The consumer will write a request to each broker it needs messages from before reading any responses. It will then block on the socket of the first broker in the list until there's a response, after which it will start processing messages; then continue with the next broker; etc.
This is by no means the optimal design, but it balances simplicity and efficiency.
> Fetch messages concurrently from all brokers

- lib/kafka/consumer.rb
- spec/consumer_spec.rb
This exception can be raised if a signal is sent to the process while it is in an `IO.select` call. Apparently, the normal `trap` is not enough.
We want to shut down gracefully in this event.
> Stop the consumer on SignalException

- lib/kafka/client.rb
This is needed so that we can support multiple PEM encoded certs in the
same file, as ruby's openssl bindings do not allow you to parse PEMs in
any other way (unless you write your own parser).
> add the ability to load an ssl certificate from a file

- Gemfile.lock
- lib/kafka/statsd.rb
- ruby-kafka.gemspec
- spec/fake_statsd_agent.rb
- spec/functional/statsd_spec.rb
Allow to monitor client activity by sending metrics to  statsd (same metrics as for datadog).
> Add Statsd monitoring

- lib/kafka/consumer_group.rb
Related to #288 
AS IS: When we kill last Kafka process in a cluster with kill -9, the connection is being retried constantly, spamming about unreachable kafka cluster in the error log. When a cluster is unreachable for a longer period of time, it results in 10s of GB in the error log.
TO BE: With a simple sleep, we will still be notified and it will still retry to connect, but the frequency will be much lower, which means that it won't spam the error log.
> #288 - busy error log spamming with unreachable kafka node

- lib/kafka/client.rb
- lib/kafka/pending_message.rb
- lib/kafka/producer.rb
- spec/fake_broker.rb
- spec/producer_spec.rb
* Call `#to_s` on arguments expected to be strings – this avoids situations where the encoder fails in the background thread.
* Make PendingMessage a normal class.
> Make `#produce` safer

- lib/kafka/offset_manager.rb
- spec/offset_manager_spec.rb
* Add tests to OffsetManager
Follow up to https://github.com/zendesk/ruby-kafka/pull/386, while adding tests to `OffsetManager`  I realized the my change broke `#seek_to_default`  😓.
> Fix OffsetManager#seek_to_default

- README.md
Hello, I've noticed, that more and more often people ask for things not directly related to ruby-kafka itself (as a lower level driver). I propose a proper section, where all the tools that are ruby-kafka dependent and that have stable development are listed.
Please move it to the top / bottom accordingly to your view on where section like that should be.
AS IS: There is no section that would point people to solutions that are ruby-kafka dependent, but that provide a higher level abstractions.
TO BE: A ```Higher level libraries``` section with all the frameworks and tools that are based on ruby-kafka (that I know), but that provide some additional functionalities and that can be used "out of the box" without having to understand how things work on a ruby-kafka and kafka level.
> higher level libraries listed in the readme proper section

- lib/kafka/connection.rb
Connections that have been idle for more than five minutes are automatically reopened. This is done in order to preempt the broker-side connection killer, which by default kicks in after 10 minutes of idleness.
> Automatically reopen idle connections

- lib/kafka/datadog.rb
I noticed that the topic was extracted from the event, but it wasn't passed into the tags for datadog. Just adding them in the places where it was missing.
> Add Topic to Datadog Metrics

- lib/kafka.rb
- lib/kafka/client.rb
- lib/kafka/pending_message.rb
- lib/kafka/producer.rb
- spec/functional/client_spec.rb
- spec/producer_spec.rb
In our application, we are consuming messages from an internal queueing system and attempting to publish them to Kafka through ruby-kafka.  If only a subset of those messages succeed, then we need to make sure that only those messages get deleted from our queueing system.  Since we have multiple processes running on this internal queue, we want to know which messages are still remaining (i.e. which ones failed) so that we don't delete those from our internal queue.
As an example, Amazon SQS consumers must explicitly mark messages as successful and any messages that failed will get picked up by another consumer at some point in the future.
There are a few ways we could address this:
(1) Change `deliver_messages` to return the list of messages that were successfully delivered. This doesn't …
> Provide access to the list of messages failed in DeliveryFailed

- lib/kafka/offset_manager.rb
When an invalid offset error was returned, we would seek the partition to the cached offset for the partition's default offset (latest/first). This change clears the cache entry beforehand so that we'll get the offset from the broker.
> Clear cached offset when seeking to default

- lib/kafka/async_producer.rb
This is an attempt to fix the cause of #422.
When there's an unexpected Kafka error, we should not crash the host application – that goes against what the async producer is there to do, which is insulate the host from Kafka problems.
Instead, we sleep for 10 seconds before restarting the background worker. This should both ensure that we don't burn crazy amounts of CPU if we run into a loop, but also that the user can look at the logs and take action.
> Restart the async producer on errors

- README.md
- lib/kafka/consumer.rb
As discussed in ##433, this PR changes the default `max_wait_time` to 1 second to avoid session timeouts in clusters with less than 20 brokers. It also updates the doc to make it clearer that this setting applies per broker.
> Change default max_wait_time

- lib/kafka/datadog.rb
If only processing messages in batches, no consumer lag information is reported to Datadog.
> Report consumer lag to Datadog when processing batches

- lib/kafka/broker.rb
- lib/kafka/broker_pool.rb
- lib/kafka/cluster.rb
- lib/kafka/connection.rb
- spec/broker_pool_spec.rb
- spec/broker_spec.rb
- spec/connection_spec.rb
This is a continuation/retry of https://github.com/zendesk/ruby-kafka/pull/291 I had some time to dig in and, hopefully, the approach here is a bit more targeted. The idea is, if the host and/or port does not match what the broker_pool has in memory, there's no chance that connections will work and the in-memory broker information needs to be evicted. We're running this in production right now and have successfully pulled and replaced brokers without causing consumers to crash and/or enter into endless connection error loops. Let me know if there's anything else I can provide/tweak to help get this on its way upstream :)
Also, there's a bonus tweak in `lib/kafka/cluster.rb` :) When testing consumer resiliency I ran in to the situation where the coordinator was updated after the response …
> Handle case where broker address changes but node_id does not

- lib/kafka.rb
- lib/kafka/consumer.rb
- lib/kafka/fetch_operation.rb
> Handle cases where there are no partitions to fetch from

- circle.yml
- lib/kafka/fetch_operation.rb
- lib/kafka/fetched_message.rb
- lib/kafka/protocol/fetch_request.rb
- lib/kafka/protocol/fetch_response.rb
- lib/kafka/protocol/message.rb
- lib/kafka/protocol/produce_request.rb
- lib/kafka/protocol/produce_response.rb
- spec/consumer_spec.rb
- spec/fake_broker.rb
- spec/test_cluster.rb
#376 was merged, effectively ending backwards compatibility with Kafka 0.9, because I thought we were ready to move off Kafka 0.9. This has proven to not be the case, so I'm not comfortable with having the main line of development (master) only be compatible with a version of Kafka I'm not personally running.
Native Kafka 0.10 support (without protocol format re-writing on the broker side) has been postponed.
> Move to the Kafka 0.10 message format (with timestamps)

- lib/kafka/consumer.rb
This is similar to a83fddfcf84e01d2f242452caa8b8a7507493916 which was applied to Consumer#each_message and ensures that offsets are retained even if we don't receive any new messages for longer than the offset retention period. It would be great if this could be backported to the v0.4-stable branch too.
> Commit offsets even if we don't read any new messages

- lib/kafka/consumer.rb
This PR aims to solve the problem of lack of offset management for topics without automatic marking. It introduces an in memory offset cache per each partition and topic. Also it supports the failure and will reconsume the whole match for ```each_batch``` and the last message for ```each_message```.
> automatically_mark_as_processed false causes infinite loop #441

- CHANGELOG.md
- lib/kafka/protocol/message.rb
- spec/compressor_spec.rb
Message sets are nested before compression. Kafka used to decompress and fix the offsets, but that no longer seems to happen, so the offsets are all wrong. We now calculate the correct offset based on the "container" message's offset and the contained message's position in the message
set.
Fixes #457.
> Correct offsets in nested message sets

- lib/kafka/client.rb
- lib/kafka/consumer.rb
- lib/kafka/fetch_operation.rb
- lib/kafka/protocol/fetch_request.rb
- spec/broker_spec.rb
This bumps the Fetch API version to v3, which supports setting a request-wide max bytes option.
Closes #467.
> Support setting the max bytes to fetch per request

- lib/kafka.rb
- lib/kafka/protocol/message_set.rb
- spec/protocol/message_set_spec.rb
When the client specifies a maximum number of bytes to read from a partition and the first message in the partition exceeds that, the broker will truncate the message set to match the client's maximum. This means that the client is unable to decode any messages.
Rather than infinitely keep asking for messages just to have a truncated message returned, we not raise MessageTooLargeToRead.
Fixes #429.
> Handle messages that exceed the maximum read size

- lib/kafka/consumer.rb
- lib/kafka/datadog.rb
- lib/kafka/statsd.rb
Since Kafka 0.10, messages have a timestamp that we can use to report the end-to-end lag.
> Report the time lag when consuming messages

- lib/kafka/connection.rb
Idle connections were causing dashboards to light up.
> Avoid raising IdleConnection from inside the instrument block

- lib/kafka/offset_manager.rb
After seeking a partition to its default offset, a consumer would try to commit -1 as the offset for the partition. This makes sure that we resolve the symbolic default offset to a physical offset number before committing.
Fixes #478.
> Fix seek to default offset behavior

- lib/kafka/producer.rb
- spec/functional/producer_spec.rb
Allows setting the `create_time` attribute when producing messages. This makes sense if e.g. the messages contain events, and you want to track end-to-end processing latency.
> Allow specifying a create time for messages

- lib/kafka/protocol/message.rb
Apparently Kafka will set the timestamp to zero when migrating pre-0.10 messages.
> Ignore invalid message timestamps

- lib/kafka/datadog.rb
It is nice to track how much data is being produced.
> Push the aggregate message size to Datadog

- lib/kafka/async_producer.rb
Now both producer emit buffer overflow with a message for consistency.
I investigated some buffer overflow issues on production, and first thought that the issue was to do with the `max_buffer_size` and `max_buffer_bytesize` settings. But the error did not include information which limit we had reached. I planned on adding a message to the exception which limit was reached, then realized that the synchronous producer already did this. Only then did I discover the `max_queue_size` setting and noticed that `BufferOverflow` was raised without a message if that limit was reached. I found the corresponding error message in the logs, so now I know that this was the problem, but I think it would be good to have both error cases handled in the same way.
> Align buffer overflow erros with sync producer

- lib/kafka/connection.rb
- lib/kafka/consumer.rb
Users shouldn't get IOError when we close down the client.
Fixes #484.
> Don't raise IOError to the user

- lib/kafka/consumer.rb
This makes it possible for subscribers to do things before the processing completes.
Closes #494.
> Instrument the start of message/batch processing

- lib/kafka/consumer.rb
- spec/consumer_spec.rb
Okay, this is a start. Not sure if this is the best place to do this. Also, I did not add the same instrumentation for `each_batch` as it would just duplicate `start_process_batch.consumer`. However, for consistency it might make sense to add it?
Let me know what you think and I'll adapt as necessary.
> Instrument fetch_batch for each_message

- lib/kafka/client.rb
- lib/kafka/cluster.rb
- lib/kafka/protocol/encoder.rb
- spec/functional/client_spec.rb
A recent version of Kafka changed its API such that an empty list of topics in the metadata request no longer causes the broker to return *all* topics in the cluster - rather, we need to pass a null value.
Fixes #493.
> Fix the list topics API

- lib/kafka/compression.rb
- lib/kafka/compressor.rb
- spec/compression_spec.rb
* Avoid instantiating a new codec instance for each message.
* Memoize more stuff.
* Add a spec.
> Refactor compression codec lookup

- lib/kafka/consumer.rb
The retry logic would sometimes cause the consumer to be stuck in a fetch loop even when it's supposed to be shutting down.
> Shut down the consumer more quickly

- lib/kafka/consumer_group.rb
Calling `member?` on a group after calling `leave` would return `true` rather than `false`, which caused double processing under some circumstances.
> Mark the consumer as not member of the group when leaving

- lib/kafka/fetch_operation.rb
- lib/kafka/fetched_message.rb
- ruby-kafka.gemspec
- spec/consumer_spec.rb
* Adds a development dependency on Stackprof.
* Optimizes `FetchedMessage` such that we don't copy variables from `Protocol::Message` unnecessarily.
> Add Stackprof and optimize stuff

- README.md
- lib/kafka/client.rb
Adds support for using the CA certs installed on your system by default for SSL. This is useful for connecting to Kafka clusters on public domains, for instance clusters hosted on public clouds.
https://ruby-doc.org/stdlib-2.0.0/libdoc/openssl/rdoc/OpenSSL/X509/Store.html
> Add support for using the system's default CA cert store

- .circleci/config.yml
- lib/kafka/broker.rb
- lib/kafka/client.rb
- lib/kafka/cluster.rb
- lib/kafka/protocol.rb
- lib/kafka/protocol/delete_topics_request.rb
- lib/kafka/protocol/delete_topics_response.rb
- spec/functional/client_spec.rb
- spec/functional/topic_management_spec.rb
The management API group already has CreateTopic API. This pull request is to implement DeleteTopicAPI. The implementation is based on official documentation https://kafka.apache.org/protocol#The_Messages_DeleteTopics. I choose API version 0 because, in the newest version, which is 1, the only difference is `throttle_time_ms` field and it seems like we don't have a proper way to handle throttling. Therefore, the version 0 is safer.
> Delete Topic API

- README.md
0.5.x is not able to write to a Kafka 0.8 cluster.
> Fix Compatibility matrix

- lib/kafka/broker.rb
- lib/kafka/client.rb
- lib/kafka/cluster.rb
- lib/kafka/protocol.rb
- lib/kafka/protocol/create_partitions_request.rb
- lib/kafka/protocol/create_partitions_response.rb
- lib/kafka/protocol/encoder.rb
- spec/functional/api_versions_spec.rb
- spec/functional/topic_management_spec.rb
```ruby
client.create_partitions_for("topic", num_partitions: 10)
```
This API is available after Kafka 1.0.0. The API is implemented based on [official documentation](https://kafka.apache.org/protocol#The_Messages_CreatePartitions). Currently, the interface doesn't support custom partition assignments because I don't think it aligns with the goal of the gem.
>  Increase topic partition count API

- README.md
Given link had an invalid anchor and was not redirecting to a proper section.
> Fix typo in local anchor

- README.md
- lib/kafka.rb
- lib/kafka/client.rb
- lib/kafka/consumer.rb
- lib/kafka/producer.rb
- spec/functional/batch_consumer_spec.rb
- spec/functional/client_spec.rb
- spec/functional/consumer_group_spec.rb
- spec/fuzz/consumer_group_spec.rb
- spec/fuzz/producer_spec.rb
- spec/spec_helper.rb
This is a required argument, and it's pretty central to the concept, so passing it as a positional argument makes sense.
> Allow passing in the seed brokers in a positional argument

- CHANGELOG.md
- lib/kafka/client.rb
- lib/kafka/cluster.rb
- lib/kafka/protocol/create_topics_request.rb
- spec/functional/topic_management_spec.rb
- spec/spec_helper.rb
I wanted to add this support so that I can create a topic that uses log compaction.
I did not add any validation of the config entry name and values here because the service will return an error if the name is not recognized or the value is invalid.
> Add support for config entries in the topic creation API

- lib/kafka/broker.rb
- spec/broker_spec.rb
- producing messages in the loop to a secured cluster with SASL.
- sync producer options: `{ max_retries: 2, retry_backoff: 1, required_acks: :all, compression_codec: :gzip }`
- messages go on `uk.test.bug.topic` topic
- shut down a broker that is a primary for the topic
- getting an exception `<Kafka::ConnectionError: Connection refused - connect(2) for 10.40.1.89:9093>`
```
...
D, [2018-03-01T15:46:32.895166 #17892] DEBUG -- : Current leader for uk.test.bug.topic/0 is node kafka-integration-2.integration.simplybusiness.co.uk:9093 (node_id=102)
I, [2018-03-01T15:46:32.895263 #17892]  INFO -- : Sending 1 messages to kafka-integration-2.integration.simplybusiness.co.uk:9093 (node_id=102)
D, [2018-03-01T15:46:32.895529 #17892] DEBUG -- : Sending produce API request 4 to …
```
> Don't fail on retry when the cluster is secured

- lib/kafka/client.rb
- spec/client_spec.rb
Hi,
I would like to reuse zookeeper's cluster information as kafka's connection information.
> support PLAINTEXT and SSL for scheme

- lib/kafka/cluster.rb
If UnknownTopicOrPartition is raised we still want to retry. It's probably because the topic has not yet been created.
> Retry another error case in `create_topic`

- lib/kafka/datadog.rb
If an application has a configured statsd client from elsewhere for publishing Datadog stats, allows it to be used for Kafka stats too.
> Add a statsd= method in the datadog integration

- README.md
- lib/kafka/broker.rb
- lib/kafka/client.rb
- lib/kafka/cluster.rb
- lib/kafka/protocol.rb
- lib/kafka/protocol/alter_configs_request.rb
- lib/kafka/protocol/alter_configs_response.rb
- lib/kafka/protocol/create_topics_request.rb
- spec/functional/topic_management_spec.rb
This PR enables the ability to update a topic's configurations via AlterConfigs API. Suggested by https://github.com/zendesk/ruby-kafka/issues/559. The usage of this API:
```ruby
kafka = Kafka.new("kafka:9092")
kafka.alter_topic("hello", 'max.message.bytes' => 1234567, 'retention.ms' => '1234567')
```
> Alter topic configurations

- lib/kafka/consumer.rb
- lib/kafka/pause.rb
- spec/pause_spec.rb
When enabled, exponential backoff will cause the pause timeout to double each time a partition is paused, until a message from the partition has been successfully processed, at which time the backoff is reset. It's possible to set a max timeout, above which we'll never pause a partition.
This will allow configuring a low initial timeout but still avoid overwhelming downstream services.
Example usage:
```ruby
begin
consumer.each_message do |message|
...
end
rescue Kafka::ProcessingError => e
consumer.pause(e.topic, e.partition, timeout: 1, max_timeout: 64, exponential_backoff: true)
end
```
> Exponential backoff for pauses

- lib/kafka/consumer.rb
- lib/kafka/pause.rb
- spec/pause_spec.rb
`#paused?` should not include the call to `#expired?`, as we need to be able to tell whether a partition is currently in a paused state but needs to be resumed because the pause duration has expired.
> Fix a bug in Pause

- lib/kafka/broker.rb
- lib/kafka/client.rb
- lib/kafka/cluster.rb
- lib/kafka/protocol.rb
- lib/kafka/protocol/list_groups_request.rb
- lib/kafka/protocol/list_groups_response.rb
- spec/functional/client_spec.rb
Adds the `ListGroups` api request and response.
See the [docs](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-ListGroupsRequest)
> Add list groups API

- lib/kafka/protocol/fetch_response.rb
- lib/kafka/protocol/record_batch.rb
- spec/functional/fetch_spec.rb
- spec/protocol/fetch_response_spec.rb
This PR is to fix the problem mentioned in https://github.com/zendesk/ruby-kafka/pull/548. New record batch format meets a serious problem with the performance. The client fires tons of fetch requests to Kafka, instead of working by batch. The main cause of this issue: FetchResponse doesn't handle the case that multiple record batches are tied together. This makes the client not aware of the number of record batches. In that case, we'll need to read to EOF and decode each record batch next to each.
In addition, there is a case which is not handled properly. Each record batch can contain in-completed series of bytes due to new max byte option in Fetch API v4. Those byte sequences doesn't provide any value and we just need to simply ignore them.
I had some benchmarks, to test out *raw …
> Fix degrading performance problem

- lib/kafka/consumer.rb
- lib/kafka/heartbeat.rb
- spec/consumer_spec.rb
This PR provides following functionalities:
- Allows to use both "forceful" and "optional" version of the heartbeat trigger
- Provides that functionality on a consumer level via `trigger_heartbeat` and `trigger_heartbeat!`
- Fixes internal heartbeat usage so all the usages are via the heartbeat method. In case of further refactor, less places to change are needed
The bang/non-bang naming convention is based on the proposed improvement for racecar (https://github.com/zendesk/racecar/issues/61).
The naming was changed not to conflict with Ruby core method`#send`.
> More consistent heartbeat API with non-optional trigger

- CHANGELOG.md
@dasch For https://github.com/zendesk/ruby-kafka/issues/601
> bring changelog upto 0.6.7

- lib/kafka/client.rb
- lib/kafka/consumer.rb
- lib/kafka/fetched_message.rb
- lib/kafka/message_buffer.rb
- lib/kafka/pending_message.rb
- lib/kafka/producer.rb
- lib/kafka/protocol/record.rb
- spec/consumer_spec.rb
- spec/functional/async_producer_spec.rb
- spec/functional/batch_consumer_spec.rb
- spec/functional/client_spec.rb
- spec/functional/consumer_group_spec.rb
- spec/functional/producer_spec.rb
- spec/producer_spec.rb
From Kafka 0.11.0, the new record batch format supports optional `headers` field for each message. This helps a lot in tracing, monitoring, as well as other stuff since it allows us to attach the metadata without messing up the main message content. The previous record batch implement PR already supports this field in record batch encoding / decoding. This PR is to implement the interfaces for the outsider to make use of this feature. The interfaces are available in `Kafka::Client` and `Kafka::Producer` and `Kafka::AsyncProducer`.
```ruby
kafka.deliver_message(
'hello', topic: 'world', headers: { 'TracingID' => 'a1234', 'SpanID' => '4567' }
)
producer = kafka.producer
producer.produce(
'hello', topic: 'world', headers: { 'TracingID' => 'a1234', 'SpanID' => '4567' }
)
```
The consumer …
> Support record headers

- lib/kafka/async_producer.rb
- spec/async_producer_spec.rb
I was wondering if there was a way to make async message delivery failures more accessible and came up with this approach. Now, when a `DeliveryFailed` or `ConnectionError` is raised after calling `deliver_messages` on the synchronous producer, it will logged to the console and instrumented so the user can learn what's causing message delivery to fail.
Do you think it's a good add? I personally think :+1: but interested in your feedback. Thanks! :)
> Add instrumenter and logger when async message delivery fails

- README.md
- lib/kafka/client.rb
- spec/client_spec.rb
Although it is highly recommended to use SASL over SSL, by enforcing SSL for SASL, ruby-kafka turns out to be unusable for those who want to not have SSL (eg: private networks) for SASL.
This PR adds a new configuration option `sasl_over_ssl ` while initializing the Kafka::Client. By default, it is set to true and the current behavior of the library will not be changed. 
For those who want to disable the strict SSL mode for SASL, they can do so by providing `sasl_over_ssl: false`.
> Disable SASL over SSL with a new config

- lib/kafka/consumer.rb
- spec/consumer_spec.rb
As is mentioned in a comment in Consumer#join_group, we need to make sure
that a consumer clears its stored offsets once it is no longer subscribed to a partition.
This is managed in the offset manager, however the consumer also keeps the offset
in `@current_offsets`, which is used for seeking when joining a group.
This may lead to a consumer seeking to an offset that is actually already processed once re-subscribing to a partition that it was subscribed to previously.
This attempt at a solution clears `@current_offsets` exactly as is done in the offset manager.
Note: I had a hard time testing the behaviour. My unit test (not included) was quite complex as I did not know how to succinctly tease joining and rejoining a group out of the consumer.
I opted to create a functional spec, however …
> Clear current offsets on join group

- README.md
- lib/kafka/client.rb
- lib/kafka/consumer.rb
- lib/kafka/consumer_group.rb
- lib/kafka/fetcher.rb
- spec/consumer_spec.rb
- spec/fetcher_spec.rb
Right now, RubyKafka exposes the lag metric only after consuming a message. There are cases where we want to see the current lag which is not currently supported:
* The consumer does not start up correctly
* The consumer starts up but is stuck on a message (e.g. it's taking too long to process and session timeout continually gets missed)
* The consumer starts up but is failing somewhere before actually getting the message
This PR adds two more places where we can instrument:
* When the consumer first starts up; this will report the current offset so the initial lag can be computed;
* Whenever a heartbeat happens, so we can report if the lag is still where it is (stuck) or has gone up. I know that in the current implementation heartbeat is tied to consuming, but I want to revisit the …
> Add more instrumentation to allow for more robust lag reporting

- lib/kafka/cluster.rb
Hi, we got high CPU loads when producing messages to 1000+ topics.
I was profiling the process with stackprof, the worst method is `Set#delete`.
In `Kafka::Cluster.add_target_topics`, `Set#-` calls `Set#delete` as many as the size of the target topics for each producing messages.
When the target topics grows large, `Set#delete` calls many times unnecessary.
This PR replace it to `Set#delete_if`. New topics are smaller than the target topics in most cases.
In our workload, this reduces CPU loads by 20-30%.
Version of Ruby: 2.5.1
```ruby
require 'benchmark'
require 'set'
MAX_TOPICS = 20
TRIALS = 10000
cl = [('a'..'z'), ('A'..'Z'), ('0'..'9')].map { |i| i.to_a }.flatten
topics = -> { (0..rand(MAX_TOPICS)).map{ (0..1).map { cl[rand(cl.length)] }.join }}
Benchmark.bmbm do |bm| …
```
> Reduce CPU loads when producing messages to many topics

- lib/kafka/client.rb
- lib/kafka/consumer.rb
- lib/kafka/fetcher.rb
In the current Fetcher and Consumer, the current implementation has a bug that leads to the situation where a huge amount of messages are skipped, without being processed. The root cause is that the fetcher doesn't handle the case where a fetched batch is empty. 
In normal scenario, it updates the current offset based on the fetched batch last offset. When the batch is empty, it updates the current offset to the highwater mark offset, which is the end of the queue. The empty batch didn't exist before. However, newer versions of Kafka (after 0.11.0, I guess) do return the empty batches in some cases:
- Control batches of transactional message production
- Throttled fetch request
- Incomplete message sets which exceed the max byte limit
- etc.
My fix is just not to update current offset …
> Fix Fetcher's message skipping 

- lib/kafka/fetch_operation.rb
- lib/kafka/fetched_batch_generator.rb
- spec/fetched_batch_generator_spec.rb
- spec/functional/compression_spec.rb
- spec/functional/consumer_group_spec.rb
When the clients send the requests to Kafka to fetch the records, say topic Hello, partition 0, from offset 3, it is expected that Kafka would return the records from offset 3 only. Surprisingly, it also returns **all the records** in the same record batch. The client doesn't handle this case for now and causes the processing duplication.
This PR is to reject out-of-scope records in fetch operation.
Fix https://github.com/zendesk/ruby-kafka/issues/635
> Fix consuming duplication due to redundant messages returned from Kafka

- CHANGELOG.md
- lib/kafka/datadog.rb
- ruby-kafka.gemspec
dogstatsd-ruby v4.0.0 moved the constants for connection defaults into a new class: https://github.com/DataDog/dogstatsd-ruby/commit/055cda22c6f029a411e86292349a73b4b53a05f2
This change keeps this gem compatible with both the old and new versions of dogstatsd-ruby.
Given that the default values represented here probably are truly constants ('127.0.0.1', 8125), it is tempting to just replicate them here. If you'd prefer that approach let me know, and I'll update this PR.
We're still using v0.6.8, so if this change is accepted I'll also backport it to the v0.6.x branch.
> Add compatibility with dogstatsd-ruby v4.0.0

- README.md
- lib/kafka/protocol/message.rb
Kafka has `log.message.format.version` configuration (and some similar ones) that allows to specify the running log format. Therefore, even connecting to Kafka 0.11.x and up, the consumers can still get the MessageSet format, instead of RecordBatch one. That breaks the consumers because there are some differences between these two formats' interfaces. Mentioned in https://github.com/zendesk/ruby-kafka/issues/646. 
I tested locally, both manually and run the test suite with `log.message.format.version` option. It is not unnecessary adding a test to CI since this case is not common.
> Fix message set backward compatible

- lib/kafka/consumer.rb
- spec/consumer_spec.rb
This PR fixes a `KeyError: key not found:...` in the offset manager https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/offset_manager.rb#L184 during rebalancing.
This happens when a partition is paused in the consumer and a rebalancing occurs in the meanwhile. When the partition pause is over we should verify that it is still assigned to our group before performing a seek. Similar verification is being done here https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/consumer.rb#L522
Low.
> Only seek if partition still belong to group

- .circleci/config.yml
- lib/kafka/consumer.rb
- lib/kafka/fetcher.rb
- spec/functional/async_producer_spec.rb
- spec/functional/idempotent_async_producer_spec.rb
- spec/functional/producer_spec.rb
- spec/functional/topic_management_spec.rb
- spec/spec_helper.rb
When creating a Fetcher instance in consumer, a thread is created to handle the commands and fetch the data in the background. That threads starts the loop right after the Fetcher is *created*. When the fetcher instance stops, that thread is still running in forever-loop. This creates serious thread leaking in some use cases where many instances of consumers are used. Therefore, I moved the thread initialization to `Fetcher#start` and kill the thread naturally when calling `Fetcher#stop`.  This change seems to be safe and more efficient. In the consumer, before starting the consumer loop, the fetcher is started. Right after the consumer loop breaks (interrupting, error, etc.), the fetcher is cleaned up and stopped totally. 
This script demonstrates the thread leaking in previous versions, …
> Create thread when starting fetcher

- CHANGELOG.md
I took a pass at updating the changelog for the next release off the v0.6-stable branch.
PR numbers reference the original PRs, not backport PRs.
> Update changelog for v0.6.9

- lib/kafka/consumer.rb
- lib/kafka/fetcher.rb
- spec/functional/consumer_group_spec.rb
As described in https://github.com/zendesk/ruby-kafka/issues/664, when a consumer re-joins a consumer group, it instructs the fetcher to asynchronously reset and seek to committed offset positions. The consumer will then continue processing fetched messages until the reset and seek take place. When the seek eventually occurs, it will seek to offsets < most recently processed messages. 
This PR tags fetched message batches with the consumer group `generation_id` that was active when fetch took place. When a consumer re-joins a group and receives an incremented `generation_id`, it passes the `generation_id` along to the fetcher reset command. Then, the consumer discards messages until it sees the current `generation_id` in fetched batches and can be assured that the reset occurred. 
An …
> Discard messages that were fetched under a previous consumer group generation

- lib/kafka/protocol/describe_groups_response.rb
- lib/kafka/protocol/message.rb
- lib/kafka/protocol/metadata_response.rb
This PR tries to avoid "warning: assigned but unused variable" which is output by Ruby when warnings are enabled.
Thanks for maintaining this gem. Thanks a lot.
> Avoid Ruby warnings about unused vars

- lib/kafka/fetcher.rb
This should fix #688 I think.
There seems to be a case where the background fetching thread starts running before `@running = true` executes. That causes the fetcher thread to shut itself down before it does any work.
> Mark fetcher as running before starting thread

- lib/kafka/round_robin_assignment_strategy.rb
- spec/functional/fetch_spec.rb
- spec/round_robin_assignment_strategy_spec.rb
In a situation where there are more consumers than partitions on all
topics, some consumers will be assigned no work at all with the current
code.
For example, with 2 topics, each with 2 partitions, and 3
consumers running, each topic's partition 0 will be assigned to the
first member ID, and partition 1 will be assigned to the second member
ID. This means 2 members with 2 partitions to consume, and 1 with
nothing!
With this change, all topic:partitions are considered together. In the
above example, 2 members would get 1 partition each, and one would be
assigned 2 partitions.
> Even out partition assignment

- lib/kafka/datadog.rb
- lib/kafka/statsd.rb
1. Track the offset lag _before_ processing a batch – if processing fails, we still want to know the lag.
2. Start tracking the size of batches. This can be important when tuning e.g. max bytes per partition in order to not overwhelm a downstream system.
> Instrument batch fetching

- lib/kafka/consumer.rb
- spec/functional/consumer_group_spec.rb
Resolves #299 
This PR certainly isn't ready to merge yet. A few notes / questions:
- This doesn't auto-discover new topics after the consumer starts - not sure what that implementation would look like
- Do you have any ideas on how to avoid the code duplication introduced in the `cluster_topics` method
- What kind of tests would be worthwhile for this?
> Introduce regex matching in Consumer#subscribe

- lib/kafka/protocol/record_batch.rb
When consuming records that were produced to kafka with the new Record format and when the `log.message.timestamp.type` configuration for the broker/topic is `LogAppendTime`, we need to fetch the record timestamp from `maxTimestamp` field and not from `FirstTimestamp + delta`. Because Kafka send `-1` as the `FirstTimestamp` in this case.
This Pr fix this.
Similar implementation can be found for other clients:
https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java#L325-L327
https://github.com/Shopify/sarama/blob/a6c1f7eaf9e4ed696183f5be645361ac97ab38bf/consumer.go#L526-L528
> use maxTimestamp for logAppendTime timestamps

- lib/kafka/consumer.rb
Sometimes our consumers fail to properly shut down. I suspect it's because, before being able to check `@running`, the consumer gets an error, e.g. RebalanceInProgress, caused by another consumer in the group shutting down. This causes a race condition, where we rejoin the group and cancel out the shutdown.
> Only rejoin group on error if we're not in shutdown mode

- lib/kafka/async_producer.rb
- lib/kafka/client.rb
- spec/async_producer_spec.rb
Related issue: https://github.com/zendesk/ruby-kafka/issues/707
> Async producer limit number of retries

- README.md
- lib/kafka.rb
- lib/kafka/client.rb
- lib/kafka/protocol/sasl_handshake_request.rb
- lib/kafka/sasl/oauth.rb
- lib/kafka/sasl_authenticator.rb
- spec/fake_server.rb
- spec/fake_token_provider.rb
- spec/protocol/sasl_handshake_request_spec.rb
- spec/sasl_authenticator_spec.rb
**Note:** _This is the same as this PR: (https://github.com/zendesk/ruby-kafka/pull/709). This one is just forked from Shopify as opposed to my personal fork. All the changes here are the last PR + any PR feedback that was left before @sam-obeid said "LGTM"!_ 
This PR adds support for OAuthBearer as a method of SASL Authentication as described in [KIP-255](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=75968876) and https://github.com/zendesk/ruby-kafka/issues/705. 
When initializing the client, the user must pass in an instance of a class that implements a `token` method (the interface is described in `lib/kafka/sasl/oauth.rb`) which returns an ID Token. 
**Example:**
```ruby
require 'ruby-kafka'
class TokenProvider
def token
"some_id_token"
end
end
client = Kafka.new( …
```
> Support SASL OAuthBearer Authentication

- lib/kafka/consumer.rb
Add missing documentation to `Consumer::each_batch` method.
Both methods `each_message` and `each_batch` raise `Kafka::ProcessingError` exception. But only the former has that declared in documentation.
There is already a unit test for method `each_batch` raising `Kafka::ProcessingError` exception.
https://github.com/zendesk/ruby-kafka/blob/master/spec/consumer_spec.rb#L439-L453
> Add missing documentation to each_batch method

- README.md
- lib/kafka/client.rb
- lib/kafka/compression.rb
- lib/kafka/compressor.rb
- lib/kafka/gzip_codec.rb
- lib/kafka/lz4_codec.rb
- lib/kafka/producer.rb
- lib/kafka/protocol/produce_request.rb
- lib/kafka/snappy_codec.rb
- lib/kafka/zstd_codec.rb
- ruby-kafka.gemspec
- spec/functional/compression_spec.rb
- spec/protocol/record_batch_spec.rb
- spec/spec_helper.rb
Kafka [now supports](https://cwiki.apache.org/confluence/display/KAFKA/KIP-110%3A+Add+Codec+for+ZStandard+Compression) zstd compression with its `2.1` release.  This does a little cleanup of codec-related code, then adds zstd compression support.
> Support zstd compression

- .gitignore
- lib/kafka/broker.rb
- lib/kafka/fetched_batch.rb
- lib/kafka/fetched_batch_generator.rb
- lib/kafka/fetched_message.rb
- lib/kafka/producer.rb
- lib/kafka/protocol.rb
- lib/kafka/protocol/add_offsets_to_txn_request.rb
- lib/kafka/protocol/add_offsets_to_txn_response.rb
- lib/kafka/protocol/txn_offset_commit_request.rb
- lib/kafka/protocol/txn_offset_commit_response.rb
- lib/kafka/transaction_manager.rb
- spec/broker_spec.rb
- spec/producer_spec.rb
- spec/transaction_manager_spec.rb
Added send_offsets_to_transaction method to Producer.
[KIP-98 ](https://cwiki.apache.org/confluence/display/KAFKA/KIP-98+-+Exactly+Once+Delivery+and+Transactional+Messaging) provides the ability to commit offsets by the producer in a transaction. This method could be used when you need to batch consumed and produced messages together, typically in a consume-transform-produce pattern with exactly once semantics.
> Producer send offsets in transaction

- lib/kafka/ssl_context.rb
- lib/kafka/ssl_socket_with_timeout.rb
The default in Ruby is to verify the certificate, but then ignore the result of that verification.
So it needs to be a structurally valid cert, but it's unrelated to the connection being opened or the CAs we've decided to trust.
This enables verification so we'll only trust certs we should trust.
It also sets the hostname so the cert presented has to correspond to the host we're connecting to.
It's possible that either of these changes could be a breaking change to someone somewhere that's using an invalid certificate without knowing it.
Example reasons:
1. It's expired and they didn't notice
2. It's not in their trust-store but they thought it was
3. It's not trusted by their system by they thought it was
4. It was a wildcard that is actually invalid, like `*.example.com` and servers …
> Verify SSL Certificates

- lib/kafka/client.rb
- lib/kafka/ssl_context.rb
The change introduced in #730 caused our application to not be able to connect to Kafka in Heroku. It looks like Heroku client certs do not have a matching hostname. This change allows the `ssl_verify_hostname` option to be passed to the `Kafka::Client`, so it can be overwritten if necessary.
/cc @kyleholzinger
> Optionally verify hostname on SSL certs

- lib/kafka/fetched_batch_generator.rb
- spec/fetched_batch_generator_spec.rb
When using MessageSets, we want to remove messages when their offset is
smaller than the requested offset.
It appears that this was handled properly for the `RecordBatch` uses cases, but not for the `MessageSet` path.
This is intended to address #745
> Do not add nil message entries when ignoring old messages.

- lib/kafka/protocol/record_batch.rb
- spec/protocol/record_batch_spec.rb
Kafka timestamps are always given in milliseconds, which is why first_timestamp was already divided by 1000 here. However, the timestamp_delta was then added as is, which is incorrect -- adding milliseconds to a timestamp in seconds will always produce the wrong result (except in the degenerate case where the delta is zero).
We could simply divide the delta by 1000 in the same way that was already being done for the first timestamp, but that would discard the sub-second part of the timestamp. Instead, first calculate the first timestamp using the full millisecond resolution (using integer arithmetic for this avoids floating point rounding errors). Then, add the delta divided by 1000 as a float to come up with each record's correct timestamp (we can't use integer arithmetic for this …
> Correctly handle timestamp deltas as milliseconds

- .circleci/config.yml
- lib/kafka/client.rb
- lib/kafka/cluster.rb
- spec/functional/config_management_spec.rb
We have methods in to manage configs, but they are not exposed to the `Kafka::Client`. This PR adds `describe_configs` and `alter_configs` to `Kafka::Client`. This useful to make per-broker changes without having to restart the service.
Also, updated CircleCI config to include testing Kafka 2.2.1.
> add client methods to manage configs

- lib/kafka/tagged_logger.rb
So it seems like `SimpleDelegator` is not always loaded by default and require explicit require 
This is the error I see after upgrading to `ruby-kafka-0.7.10`
```
NameError: uninitialized constant Kafka::SimpleDelegator
/bundle/gems/ruby-kafka-0.7.10/lib/kafka/tagged_logger.rb:7:in `<module:Kafka>'
/bundle/gems/ruby-kafka-0.7.10/lib/kafka/tagged_logger.rb:6:in `<top (required)>'
/bundle/gems/ruby-kafka-0.7.10/lib/kafka/client.rb:17:in `require'
/bundle/gems/ruby-kafka-0.7.10/lib/kafka/client.rb:17:in `<top (required)>'
/bundle/gems/ruby-kafka-0.7.10/lib/kafka.rb:373:in `require'
/bundle/gems/ruby-kafka-0.7.10/lib/kafka.rb:373:in `<top (required)>'
/bundle/gems/racecar-0.4.2/lib/racecar/runner.rb:1:in `require'
/bundle/gems/racecar-0.4.2/lib/racecar/runner.rb:1:in `<top (required)>' …
```
> SimpleDelegator is not loaded by default and require implicit require

- ruby-kafka.gemspec
- spec/spec_helper.rb
This addresses the build issue seen in #770, to restore support for Rails 6.0.
Based on https://guides.rubyonrails.org/active_support_core_extensions.html#stand-alone-active-support, `active_support` should be required. That doesn't actually load much, but then when `active_support/notifications` is required the other relevant dependencies will be found.
Still needs to require  `active_support/core_ext/object/try` to work around a missing require within active_support/notifications. This has been fixed on master here: https://github.com/rails/rails/commit/530f7805ed5790af1d472a041bc74089dc183f47#diff-7d21210eb262dd39635c5b4952d29dee
> Support Rails 6.0, require active_support for specs

- lib/kafka/async_producer.rb
- lib/kafka/prometheus.rb
- ruby-kafka.gemspec
- spec/prometheus_spec.rb
We needed prometheus metrics and were already using the 0.10.0.pre.alpha2 branch for prometheus-client.  This PR has updates that conform to the breaking API changes in that prometheus-client version.
I realize this is targeting an alpha version of prometheus-client, so I didn't know if you wanted to support that or not, but I figured I would make this PR for anyone else who needed the same support.
> Prometheus v0.10.0.pre.alpha2 api

- lib/kafka/client.rb
- lib/kafka/consumer_group.rb
- lib/kafka/protocol/join_group_request.rb
- spec/functional/client_spec.rb
If we send a JoinGroupRequest v0 message to join an existing consumer group, the broker does not wait for other members to send their own JoinGroupRequests, resulting in all other members being kicked out of the group. When they rejoin later, the same thing happens, resulting in the group continually being rebalanced with a single member each time.
Sending a JoinGroupRequest v1 message instead lets us specify a timeout to wait for other members. A new member is now added to the consumer group as expected, rather than becoming the only member.
The default value of 1 minute for rebalance_timeout is taken from what Sarama (Go library) does. librdkafka defaults to 5 minutes here, which seems a little excessive.
This will break if talking to a Kafka broker older than 0.10.1. This is unlikely …
> Send JoinGroupRequest v1 messages with rebalance timeouts

- lib/kafka/async_producer.rb
- lib/kafka/client.rb
- lib/kafka/producer.rb
- spec/async_producer_spec.rb
- spec/client_spec.rb
- spec/producer_spec.rb
One of my users (I maintain a library that wraps ruby-kafka) was producing asynchronously with the topic argument being a Symbol, but they weren't seeing problems until messages couldn't be added to the async message queue because the thread producer couldn't deliver messages with Symbol topics.
The proposed code ensures that `topic` is either a String or a Symbol upfront (every Ruby object has a String representation, and while a Symbol makes sense, a Hash doesn't, so the code needs to explicitly typecheck `topic`).
I updated all 3 producing methods because it seems nicer to have a uniform, and explanatory error message (the previous one was a `NoMethodError` about a method named `bytesize`).
If y'all don't want to allow Symbols, let me know, and I'll change it to only allow Strings.
If …
> AsyncProducer#produce should fail fast if `topic` is a "bad" type

- lib/kafka/connection.rb
- lib/kafka/fetcher.rb
We've noticed warnings when calling 
- `open?` like on https://github.com/zendesk/ruby-kafka/blob/v0.7.10/lib/kafka/connection.rb#L98
- `idle?` like on https://github.com/zendesk/ruby-kafka/blob/v0.7.10/lib/kafka/connection.rb#L94 
To fix this, we're defining them in the initializer.  
Those interrogator methods already check if those instance variables are non-nil so defining them will be safe.
> Define instance variables to avoid warnings

- .circleci/config.yml
- README.md
adds [kafka 2.3.1](https://www.apache.org/dist/kafka/2.3.1/RELEASE_NOTES.html) to the CI tests
had to open a new PR since https://github.com/zendesk/ruby-kafka/pull/769 was closed while waiting for [wurstmeister 2.3.1](https://github.com/wurstmeister/kafka-docker/pull/536)
> kafka 2.3.1

- .circleci/config.yml
- README.md
adds [kafka 2.4.0](https://www.apache.org/dist/kafka/2.4.0/RELEASE_NOTES.html) to the CI tests
> kafka 2.4.0

- lib/kafka/cluster.rb
- spec/cluster_spec.rb
Resolves #802 
Currently nil or empty string topic is basically allowed and will raise `Kafka::ConnectionError` (`Connection error EOFError`) in `Cluster#fetch_cluster_info` which is confusing.
Actually nil raises error due to #791 (nil has not to_str) , but there are still 2 problems.
* Empty string as topic is allowed in `Producer#produce` and `Kafka::DeliveryFailed` will be raised in `Producer#deliver_messages` which is still confusing.
* Some libraries (ex fluent-plugin-kafka) uses internal class directly and still raises `Kafka::ConnectionError` with nil topic.
This PR raises ArgumentError with nil or empty topic in `Cluster#add_target_topics` to resolve these problems.
> Fix confusing error message with nil or empty string topic

- lib/kafka/datadog.rb
- ruby-kafka.gemspec
After cloning https://github.com/zendesk/ruby-kafka and following the development instructions to run `bin/setup` and then `rake spec` I encountered a number of failed specs with errors that looked like this:
```
NameError:
uninitialized constant Datadog::Statsd::Connection::DEFAULT_HOST
Did you mean?  Datadog::Statsd::DEFAULT_BUFFER_SIZE
```
Applied suggestion from @tjwp in https://github.com/zendesk/ruby-kafka/pull/810#issuecomment-589415255.
> Fix missing constant errors

- lib/kafka/consumer.rb
- lib/kafka/datadog.rb
- spec/prometheus_spec.rb
My team at GitHub uses racecar version 1.0.1 and by extension ruby-kafka. We're interested in the potential of racecar 2 that uses the rdkafka-ruby client but we heavily rely on the `consumer.offset_lag` metric for monitoring our stream processors.
It doesn't look like that metric is going to be straightforward to implement in racecar 2 but I'm wondering if we could instead switch to the `consumer.time_lag` metric instead? Unfortunately that metric isn't published in the `process_batch.consumer` payload in racecar 1.0.1 or racecar 2.0.0-beta.
This PR updates the `process_batch.consumer` payload to include a `last_create_time` metric which comes from the last message in the batch. 
We could use a fork of `ruby-kafka` with these changes to accomplish our goal with racecar 1.0.1 in the short …
> Instrument create_time from last message in batch

- lib/kafka/client.rb
- lib/kafka/protocol/metadata_response.rb
- spec/functional/client_spec.rb
For tooling / automation scripts, it would be super helpful to expose a method in the client object for querying a topic's replica count, which is possible from the `cluster.partitions_for` function. 
https://github.com/zendesk/ruby-kafka/blob/1b2ed7cd0c79d4ae7e915c4be616df6f59a93eba/lib/kafka/cluster.rb#L180
Another option could be to write a client function that returns the full partition array instead of just the `count` then I can grab the replica count from my code.
https://github.com/zendesk/ruby-kafka/blob/1b2ed7cd0c79d4ae7e915c4be616df6f59a93eba/lib/kafka/client.rb#L694
Let me know what you think or if there's a better place for this.
> Add client function for fetching topic replica count

- lib/kafka/client.rb
- lib/kafka/consumer.rb
- spec/consumer_spec.rb
- spec/functional/consumer_group_spec.rb
- Enable consumers to automatically subscribe to the new topics that match the regex
- This feature is not enabled by default to keep the backward compatibility
> [Feat] Allow consumers to refresh the topic lists

- lib/kafka/consumer.rb
This PR removes an unnecessary reconnection after `Kafka::Consumer#stop` is called.
`@cluster.disconnect` closes the connections to all brokers including the coordinator in spite of the fact that `@group.leave` requires a connection to the coordinator, so call `@cluster.disconnect` after `@group.leave`.
You can confirm the behavior by executing the following script:
```ruby
require "kafka"
CLIENT_ID = ENV["CLIENT_ID"]
GROUP_ID = ENV["GROUP_ID"]
TOPIC = ENV["TOPIC"]
$stdout.sync = true
logger = Logger.new($stdout)
logger.level = Logger::DEBUG
kafka = Kafka.new(["localhost:9092"], client_id: CLIENT_ID, logger: logger)
consumer = kafka.consumer(group_id: GROUP_ID)
consumer.subscribe(TOPIC)
Thread.new do
sleep 5
consumer.stop
end
consumer.each_message do |message|
puts message.topic, …
```
> Disconnect after leaving the group

- .gitignore
- lib/kafka/consumer.rb
- lib/kafka/fetcher.rb
This an attempt to fix https://github.com/zendesk/ruby-kafka/issues/823 that causes consumer to sleep for 2 seconds and thus causing an avg 1.5 second pause between when a message is published and then started to be processed by a consumer.
Note that my fix is based on research done by https://github.com/paneq in the above issue.
> Issue 823 > Use max_wait_time while sleeping in fetch_batches

- .circleci/config.yml
- README.md
Docker images were [recently added](https://github.com/wurstmeister/kafka-docker/pull/589) for kafka 2.5, so update CI tests to use the new version.
> Add kafka 2.5 to CI

- README.md
- lib/kafka/client.rb
- lib/kafka/ssl_context.rb
Resolves https://github.com/zendesk/ruby-kafka/issues/826
@dasch
> Make verify_hostname settable for ssl contexts

- lib/kafka/datadog.rb
- spec/datadog_spec.rb
- spec/fake_datadog_agent.rb
- spec/functional/datadog_spec.rb
dogstatsd-ruby has supported Unix domain socket (cf. https://github.com/DataDog/dogstatsd-ruby/pull/61), and I want to use it.
> Support Unix domain socket in Kafka::Datadog

- lib/kafka/offset_manager.rb
- spec/offset_manager_spec.rb
This pull request resolves an edge case, but one that represents a **_critical_** bug for us that has caused us a very significant amount of pain over the last couple years, but has also been quite elusive to nail down.
We have a system that needs to buffer a certain number of messages and insert them into another system all at once as a batch, in a SQL transaction.
To do this, inside the `each_message` loop, we add messages to an array until we've accumulated enough for a batch. Once the buffer is large enough, we atomically export the batch to the external system, call `mark_message_as_processed` for each buffered message, and clear the buffer.
The problem we've encountered several times now is that the consumer group may rebalance and end up with different partition assignments before …
> Critical bug fix: Extra sanity checking when marking offsets as processed

- ruby-kafka.gemspec
It is better to use SPDX ID for license field.
https://guides.rubygems.org/specification-reference/#license=
The list of licenses:
https://spdx.org/licenses/
> Use the standard SPDX ID for license in gemspec

- lib/kafka/consumer_group.rb
Addresses [this](https://app.circleci.com/pipelines/github/zendesk/ruby-kafka/46/workflows/a633c3e5-e1f0-4dd8-b54a-e3c37beb16a6/jobs/4849) and [this](https://app.circleci.com/pipelines/github/zendesk/ruby-kafka/48/workflows/79b9c0db-e5ab-44e0-8d21-c86b8aba459b/jobs/4876) CI failure. Both seem to be ephemeral problems caused by the Kafka cluster being in an initializing state.
> Add some hardening

- spec/consumer_spec.rb
Minor cleanup of a spec. You don't need a counter variable to setup multiple return values.
> Cleanup setting of consecutive return values in stubs

- lib/kafka/client.rb
- lib/kafka/consumer.rb
- lib/kafka/interceptors.rb
- lib/kafka/producer.rb
- spec/consumer_spec.rb
- spec/fake_consumer_interceptor.rb
- spec/fake_producer_interceptor.rb
- spec/functional/interceptors_spec.rb
- spec/producer_spec.rb
Add producer and consumer interceptors that can intercept messages at different points on producer and consumer in order to trace the path of individual messages across the cluster.
- inspired in [KIP-42](https://cwiki.apache.org/confluence/display/KAFKA/KIP-42%3A+Add+Producer+and+Consumer+Interceptors#KIP42:AddProducerandConsumerInterceptors-Motivation)
- intercepts produced messages before they are sent to the brokers
- intercepts consumed messages before are returned to the client
- does not intercept the broker's acknowledgement
- does not intercept when the consumer commits
> add producer consumer interceptors

- lib/kafka/consumer.rb
From the comment: `It seems it doesn't need to be threadsafe.`
Via https://github.com/zendesk/ruby-kafka/pull/835#issuecomment-646030465
I took a quick look and it seems it's safe to use a simple Hash
Fixes: https://github.com/zendesk/ruby-kafka/issues/842
Fixes: https://github.com/zendesk/ruby-kafka/issues/840
> remove concurrent map and use a Hash

- lib/kafka/async_producer.rb
See the commit messages for details.
> Various AsyncProducer improvements

- lib/kafka/consumer_group.rb
This PR changes the log-level of the `RebalanceInProgress` exception in `ConsumerGroup#heartbeat` to `warning` as discussed in #847.
Resolves #847.
> Log RebalanceInProgress in ConsumerGroup#heartbeat as warning

- README.md
Instead of `verify_hostname`, the acceptable parameter for `Kafka` class constructor is `ssl_verify_hostname`. Current readme is kind of confusing, I personally tried the parameter `verify_hostname`, but this failed.
> change parameter to ssl_verify_hostname in readme

- lib/kafka/async_producer.rb
Ruby 2.7 deprecates automatic conversiom between positional and keyword
arguments.
See: https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/
Resolves: #857
> Positional and keyword argument handling in Ruby 2.7

- lib/kafka/transaction_manager.rb
- spec/transaction_manager_spec.rb
The use of generic RuntimeError exceptions coming from the `TransactionManager` requires brittle error-handling in dependant code, so I've changed most of the `raise` statements in the `TransactionManager` to use the `Kafka::InvalidTxnStateError` exception.
Additionally, there may be cases where dependant code starts a transaction using the producer's `#transaction` block syntax and then an exception is raised within that block *before* the transaction manager actually opens up a transaction. In such cases, prior to this change, the real exception is obfuscated, because the transaction manager would raise an exception
about not being in a valid transactional state.
With this change, attempting to abort a transaction that has not actually been opened will no longer result in an exception. …
> Improved Exceptions in TransactionManager

- .circleci/config.yml
- spec/spec_helper.rb
- spec/transaction_manager_spec.rb
This PR resolves a deprecation warning like below when the Ruby version is 2.7:
```
/path/to/ruby-kafka/spec/transaction_manager_spec.rb:594: warning: Passing the keyword argument as the last hash parameter is deprecated
/path/to/ruby-kafka/spec/transaction_manager_spec.rb:682: warning: The called method `txn_offset_commit_response' is defined here
```
```
% rspec --tag functional spec/transaction_manager_spec.rb:601 spec/functional/consumer_group_spec.rb:438
Run options:
include {:functional=>true, :locations=>{"./spec/transaction_manager_spec.rb"=>[601], "./spec/functional/consumer_group_spec.rb"=>[438]}}
exclude {:performance=>true, :fuzz=>true}
Kafka::TransactionManager
#send_offsets_to_txn
currently in transaction
/Users/arabiki/ghq/src/github.com/zendesk/ruby-kafka/spec/transaction_m …
```
> Resolve "Passing the keyword argument as ..." deprecation warning

- .circleci/config.yml
- spec/async_producer_spec.rb
This PR resolves `RSpec::Mocks::OutsideOfExampleError` when spec/async_producer_spec.rb is executed.
```
% rspec spec/async_producer_spec.rb
Run options: exclude {:functional=>true, :performance=>true, :fuzz=>true}
Kafka::AsyncProducer
#deliver_messages
instruments the error after failing to deliver buffered messages
#shutdown
delivers buffered messages
instruments a failure to deliver buffered messages
#produce
delivers buffered messages
retries until configured max_retries
requires `topic` to be a String
Finished in 0.73698 seconds (files took 0.63537 seconds to load)
6 examples, 0 failures
#<Thread:0x00007fc7ab171c70 /Users/arabiki/ghq/src/github.com/zendesk/ruby-kafka/lib/kafka/async_producer.rb:162 aborting> terminated with exception (report_on_exception is true):
Traceback (most …
```
> Resolve RSpec::Mocks::OutsideOfExampleError

- .circleci/config.yml
- spec/functional/consumer_group_spec.rb
In the example, one consumer sometimes consumers all messages before another consumer joins. As a result, the example is unstable. This PR makes it stable by ensuring all consumers have joined.
> Make "consuming messages with a custom assignment strategy" stable

- .circleci/config.yml
- README.md
- spec/functional/topic_management_spec.rb
adds [kafka 2.7.0](https://downloads.apache.org/kafka/2.7.0/RELEASE_NOTES.html) to the CI tests
> kafka 2.7.0

- CHANGELOG.md
- README.md
- lib/kafka/client.rb
- lib/kafka/cluster.rb
- spec/cluster_spec.rb
By default, the Java implementation of a Kafka client can use each returned IP address from a hostname.
cf. https://kafka.apache.org/documentation/#client.dns.lookup
librdkafka also does:
> If host resolves to multiple addresses librdkafka will
> round-robin the addresses for each connection attempt.
cf. https://github.com/edenhill/librdkafka/blob/v1.5.3/INTRODUCTION.md#brokers
Such a feature helps us to manage seed brokers' IP addresses easily, so this PR implements it.
> Support seed brokers' hostname with multiple addresses

- lib/kafka/cluster.rb
- lib/kafka/protocol/encoder.rb
This PR resolves the following warnings:
```
% yard doc
[warn]: @param tag has unknown parameter name: group_id:
in file `lib/kafka/cluster.rb' near line 122
[warn]: @param tag has unknown parameter name: transactional_id:
in file `lib/kafka/cluster.rb' near line 132
[warn]: @param tag has unknown parameter name: string
in file `lib/kafka/protocol/encoder.rb' near line 131
-- snip --
```
> Fix "@param tag has unknown parameter name"

- lib/kafka/protocol/record_batch.rb
Control batches can show up even outside of transactions. This change drops the requirement that you must be in a transaction for a record to be labeled a control batch.
All tests pass with this change. 
This change is very similar to the ones made in other Kafka clients: 
- Sarama: https://github.com/Shopify/sarama/pull/1898
- librdkafka: https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_msgset_reader.c#L860
> Updated to ignore all control batches

- CHANGELOG.md
- lib/kafka/protocol/sync_group_response.rb
- spec/protocol/sync_group_response_spec.rb
When the error code is non-zero there isn't necessarily (ever?) an assignment. Currently the decoder raises a `TypeError` ("no implicit conversion of nil into String") - this updates the logic to only try to decode the assignment if there are any bytes.
> Handle SyncGroup responses with a non-zero error and no assignments

- CHANGELOG.md
- lib/kafka/client.rb
This introduces a very small change, to ensure a stale cluster gets its metadata refreshed when using `Kafka::Client#deliver_message`
See #900 for details and motivation
> Refresh metadata if necessary on deliver_message

- CHANGELOG.md
- lib/kafka/consumer_group.rb
- lib/kafka/round_robin_assignment_strategy.rb
- spec/functional/consumer_group_spec.rb
- spec/round_robin_assignment_strategy_spec.rb
There are 2 issues that currently prevent supporting this feature:
1. **The current `RoundRobinAssignmentStrategy` assumes all subscriptions are equal**
We need a more generalized algorithm to perform assignments now that we have different subscriptions across the consumer group. This PR introduces a new additional strategy heavily inspired in the java kafka client [RoundRobinAssignor](https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/consumer/RoundRobinAssignor.java) that properly handle this case.
2. **The leader consumer thread assumes that all consumers subscription are equivalent**
If different consumers were to have different topic subscription we can't rely on the in-memory `@topics` variable to produce correct assignments. Instead, we can …
> ISSUE-525 / 764: ruby-kafka does not support different topic subscriptions in the same consumer group

- lib/kafka/client.rb
- lib/kafka/ssl_context.rb
- spec/ssl_context_spec.rb
A proposed change to facilitate fixing https://github.com/fluent/fluent-plugin-kafka/issues/287. It would help to avoid parsing certs in the upper level code that should not need to know how to do that.
> Make ssl_ca_cert_file_path support an array of files

- lib/kafka/async_producer.rb
On `rescue Kafka::Error` we're rerunning the whole method block
including `@logger.push_tags(@producer.to_s)`, but clearing tags
only in `ensure` which is not run on `retry`, so each retry adds
another one `[Producer name]` to tags and, as a consequence, all
the log messages after that.
> Fix multiple `[Producer name]` tags on failures

- lib/kafka/datadog.rb
The `topic` key is already being set in `tags`, so these method calls don't actually do anything.
> Avoid unnecessary Hash merges

- .circleci/config.yml
This PR updates `.circleci/config.yml` to use CircleCI matrix jobs.
It can make it easy to test with multiple Ruby and Kafka versions, and also can simplify duplicate statements.
Here are the details:
- Upgrade to next-gen Docker convenience images
The following message is shown in Circle CI job page.
> You’re using a [deprecated Docker convenience image.](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034) Upgrade to a next-gen Docker convenience image.
The link above states the following.
> Moving from a legacy to next-gen image requires a change to the namespace. All legacy images have a Docker namespace of circleci, while next-gen images have a Docker namespace of cimg. For example, migrating from the legacy Ruby or Python image to the respective next-gen image …
> Use CircleCI matrix jobs to test with the latest version
